//! Environment activation: one canonical, mode-0600 `~/.env` fragment, the Git
//! configuration and helper hooks, the interactive-shell profile, and the
//! optional `.agents/resume` hook.
//!
//! Core sends `environment.check {generation, digest}` first; only when the
//! daemon does not hold that exact activation does Core send the full
//! `environment.activate`. Materialization runs on a blocking worker so the
//! connection loop keeps heartbeating while a resume hook runs.

use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use cap_std::fs::{Dir, OpenOptions};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::fs;
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::Duration;

pub const STATE_DIRECTORY: &str = "/home/user/.local/state/dx-terminal";
pub const GIT_CONFIG_FILE: &str = "gitconfig";
/// The shell hook dxd owns, in its state directory. In the guest the static
/// root stub `/etc/profile.d/dx-terminal.sh` (`assets/dx-terminal-stub.sh`)
/// sources it; locally bash reads it as its rcfile.
pub const PROFILE_FILE: &str = "profile";
pub const ENVIRONMENT_FILE: &str = ".env";
pub const MAX_ENVIRONMENT_ENTRIES: usize = 300;
pub const MAX_VALUE_BYTES: usize = 32_768;
pub const MAX_TOTAL_VALUE_BYTES: usize = 9_830_400;
pub const MAX_FRAGMENT_BYTES: usize = 40 * 1_024 * 1_024;
pub const RESUME_TIMEOUT: Duration = Duration::from_secs(120);

pub const PROFILE_HOOK: &str = include_str!("../assets/dx-terminal-profile.sh");
#[cfg(test)]
const PROFILE_STUB: &str = include_str!("../assets/dx-terminal-stub.sh");

const LEGACY_ENVIRONMENT_FILE: &str = "environment";
pub(crate) const ENVIRONMENT_HEADER: &[u8] = b"# Generated by dx\n\
# Contains entries from dx Secrets & Environment Variables settings\n\
# (personal, project, and workspace scopes; project entries override workspace entries,\n\
# and personal entries override both).\n\
# Manage entries at their source in dx Personal, Project, or Workspace Settings.\n";

const RESERVED_NAMES: &[&str] = &[
    "BASHPID",
    "BASHOPTS",
    "BASH_ENV",
    "BASH_VERSION",
    "BASH_VERSINFO",
    "BETTER_AUTH_SECRET",
    "CI",
    "COLUMNS",
    "DX_ACCESS_AUDIENCE",
    "DX_ACCESS_ISSUER",
    "DX_AUTH_TRUSTED_ORIGINS",
    "DX_AUTH_URL",
    "DX_CONFIG_ENCRYPTION_KEYS",
    "DX_E2B_TEMPLATE",
    "DX_E2B_TIMEOUT_MS",
    "DX_ENV",
    "DX_EXPERIMENTAL_FEATURE_FIXTURE",
    "DX_INTEGRATION_FORGEJO_OAUTH",
    "DX_INTEGRATION_GITHUB_APP",
    "DX_INTEGRATION_GITLAB_OAUTH",
    "DX_MANAGED_SSH_SIGNING_ENABLED",
    "DX_MODEL_DEPLOYMENT_PROVIDERS",
    "DX_MODEL_ENDPOINT_ALLOWLIST",
    "DX_RUNNER_PROFILE_CATALOG",
    "DX_STORAGE",
    "DX_WORKLOAD_IDENTITY_SOCKET",
    "ENV",
    "E2B_API_KEY",
    "EUID",
    "HISTFILE",
    "HISTFILESIZE",
    "HISTSIZE",
    "HOME",
    "HOSTNAME",
    "IFS",
    "LD_LIBRARY_PATH",
    "LD_PRELOAD",
    "LINES",
    "LOGNAME",
    "NODE_OPTIONS",
    "PATH",
    "PPID",
    "PWD",
    "SHELL",
    "SHELLOPTS",
    "SHLVL",
    "TERM",
    "TMUX",
    "TMUX_PANE",
    "UID",
    "USER",
    "_",
];

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EnvironmentEntry {
    pub name: String,
    pub value_base64_url: String,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EnvironmentActivate {
    pub generation: u64,
    pub entries: Vec<EnvironmentEntry>,
    pub git: GitConfiguration,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EnvironmentCheck {
    pub generation: u64,
    pub digest: String,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct GitConfiguration {
    pub author_name: String,
    pub author_email: String,
    pub thread_url: String,
    pub signing_enabled: bool,
    pub bitbucket_gateway: Option<GitBitbucketGateway>,
}

fn git_config_value(value: &str) -> String {
    let escaped = value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\t', "\\t");
    format!("\"{escaped}\"")
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct GitBitbucketGateway {
    pub origin: String,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum EnvironmentOutcome {
    Applied,
    Unchanged,
    Superseded,
    Unavailable,
    /// `environment.check` did not match the applied activation; send it.
    Missing,
    /// The `.agents/resume` hook exceeded its time bound.
    ResumeTimeout,
}

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum EnvironmentShell {
    NoShell,
    Current,
    RestartRequired,
}

#[derive(Serialize)]
pub struct EnvironmentResult {
    pub kind: EnvironmentOutcome,
    pub generation: u64,
    pub shell: EnvironmentShell,
}

#[derive(Clone)]
pub struct EnvironmentPaths {
    state_directory: PathBuf,
    home: PathBuf,
    user: String,
}

impl EnvironmentPaths {
    pub fn production() -> Self {
        Self {
            state_directory: PathBuf::from(STATE_DIRECTORY),
            home: PathBuf::from("/home/user"),
            user: "user".into(),
        }
    }

    pub fn local(home: PathBuf, state_root: PathBuf) -> Self {
        Self {
            state_directory: state_root.join("dx-terminal"),
            home,
            user: std::env::var("USER")
                .or_else(|_| std::env::var("USERNAME"))
                .unwrap_or_else(|_| "user".into()),
        }
    }

    #[cfg(test)]
    fn test(root: &Path) -> Self {
        Self {
            state_directory: root.join("state"),
            home: root.join("home"),
            user: "user".into(),
        }
    }
}

/// Result of a materialization the connection loop applies to the terminal.
pub struct Materialized {
    pub generation: u64,
    pub values: BTreeMap<String, String>,
    pub changed: bool,
    pub digest: String,
    pub outcome: EnvironmentOutcome,
    /// Hash of the `.env` and Git configuration bytes as written, when known.
    files: Option<String>,
}

pub struct EnvironmentRuntime {
    paths: EnvironmentPaths,
    applied_generation: u64,
    applied_digest: Option<String>,
    /// Hash of the files this process last wrote for `applied_digest`.
    applied_files: Option<String>,
    pending_generation: Option<u64>,
    pending_changed: bool,
}

impl EnvironmentRuntime {
    /// Also writes this release's shell hook, so shells started after a
    /// self-update get it without waiting for an activation.
    pub fn new(paths: EnvironmentPaths) -> Self {
        if let Err(error) = install_profile(&paths) {
            eprintln!("dxd could not write its shell profile: {error}");
        }
        Self {
            paths,
            applied_generation: 0,
            applied_digest: None,
            applied_files: None,
            pending_generation: None,
            pending_changed: false,
        }
    }

    /// Answer `environment.check` without touching the worker: the digest
    /// must be the one this process applied and the `.env` and Git
    /// configuration on disk must still be the bytes it wrote. Any later edit
    /// answers `missing`, so Core rewrites them. Core numbers every activation afresh, so a
    /// later generation with the same digest is the same environment: adopt
    /// it, unless an activation is still pending.
    pub fn check(&mut self, check: &EnvironmentCheck) -> EnvironmentOutcome {
        if check.generation == 0 || check.generation > 9_007_199_254_740_991 {
            return EnvironmentOutcome::Unavailable;
        }
        if check.generation < self.applied_generation {
            return EnvironmentOutcome::Superseded;
        }
        if (check.generation == self.applied_generation || self.pending_generation.is_none())
            && self.applied_digest.as_deref() == Some(check.digest.as_str())
            && self.applied_files.is_some()
            && written_files(&self.paths).ok() == self.applied_files
        {
            self.applied_generation = check.generation;
            EnvironmentOutcome::Unchanged
        } else {
            EnvironmentOutcome::Missing
        }
    }

    /// Validate and classify an activation before the blocking work starts.
    pub fn admit(
        &mut self,
        operation: &EnvironmentActivate,
    ) -> Result<Admitted, EnvironmentOutcome> {
        let generation = operation.generation;
        if generation == 0 || generation > 9_007_199_254_740_991 {
            return Err(EnvironmentOutcome::Unavailable);
        }
        if generation < self.applied_generation {
            return Err(EnvironmentOutcome::Superseded);
        }
        let values =
            decode_entries(&operation.entries).map_err(|_| EnvironmentOutcome::Unavailable)?;
        let retrying_pending = self.pending_generation == Some(generation);
        self.pending_generation = Some(generation);
        Ok(Admitted {
            paths: self.paths.clone(),
            generation,
            values,
            git: operation.git.clone(),
            digest: activation_digest(operation),
            applied_generation: self.applied_generation,
            retrying_pending,
            pending_changed: self.pending_changed,
        })
    }

    /// Record the outcome of a blocking materialization.
    pub fn complete(&mut self, materialized: &Materialized) {
        match materialized.outcome {
            EnvironmentOutcome::Applied | EnvironmentOutcome::Unchanged => {
                self.applied_generation = materialized.generation;
                self.applied_digest = Some(materialized.digest.clone());
                self.applied_files = materialized.files.clone();
                self.pending_generation = None;
                self.pending_changed = false;
            }
            _ => {
                self.pending_changed |= materialized.changed;
            }
        }
    }
}

/// Everything the blocking materialization needs, detached from the runtime.
pub struct Admitted {
    paths: EnvironmentPaths,
    pub generation: u64,
    values: BTreeMap<String, String>,
    git: GitConfiguration,
    digest: String,
    applied_generation: u64,
    retrying_pending: bool,
    pending_changed: bool,
}

impl Admitted {
    /// Materialize on the current (blocking) thread.
    pub fn materialize(self, workspace_root: &Path) -> Materialized {
        let generation = self.generation;
        let digest = self.digest.clone();
        let (outcome, changed) = match materialize(&self, workspace_root) {
            Ok(changed) => (
                if changed {
                    EnvironmentOutcome::Applied
                } else {
                    EnvironmentOutcome::Unchanged
                },
                changed,
            ),
            Err(MaterializeError::ResumeTimeout(changed)) => {
                (EnvironmentOutcome::ResumeTimeout, changed)
            }
            Err(MaterializeError::Io) => (EnvironmentOutcome::Unavailable, false),
        };
        let files = matches!(
            outcome,
            EnvironmentOutcome::Applied | EnvironmentOutcome::Unchanged
        )
        .then(|| written_files(&self.paths).ok())
        .flatten();
        Materialized {
            generation,
            values: self.values,
            changed,
            digest,
            outcome,
            files,
        }
    }
}

enum MaterializeError {
    Io,
    ResumeTimeout(bool),
}

impl From<io::Error> for MaterializeError {
    fn from(_: io::Error) -> Self {
        Self::Io
    }
}

fn materialize(admitted: &Admitted, workspace_root: &Path) -> Result<bool, MaterializeError> {
    let paths = &admitted.paths;
    let values = &admitted.values;
    let state_directory = ensure_state_directory(paths)?;
    let home = open_home_directory(paths)?;
    install_git_config(&paths.state_directory, &admitted.git)?;
    install_profile(paths)?;
    ensure_history(&state_directory)?;
    let existing = inspect_fragment(&home, ENVIRONMENT_FILE)?;
    if admitted.generation == admitted.applied_generation
        && existing
            .as_ref()
            .is_none_or(|fragment| fragment.values != *values)
    {
        return Err(io::Error::other("applied generation drifted").into());
    }
    let changed = existing
        .as_ref()
        .is_none_or(|fragment| fragment.values != *values);
    let generated = generate_fragment(values)?;
    if changed {
        replace_fragment(&home, ENVIRONMENT_FILE, &generated)?;
    } else {
        sync_dir(&home)?;
    }
    remove_legacy_fragment(&state_directory)?;
    let should_resume = changed || admitted.applied_generation == 0 || admitted.retrying_pending;
    if should_resume {
        match run_resume(workspace_root, values, paths) {
            Ok(()) => {}
            Err(ResumeError::Timeout) => {
                return Err(MaterializeError::ResumeTimeout(
                    changed || admitted.pending_changed,
                ));
            }
            Err(ResumeError::Io(error)) => return Err(error.into()),
        }
    }
    Ok(changed || admitted.pending_changed)
}

/// Deterministic digest of an activation, shared with Core.
pub fn activation_digest(operation: &EnvironmentActivate) -> String {
    let mut hasher = Sha256::new();
    hasher.update(b"dxd-environment-digest-v1\n");
    for entry in &operation.entries {
        hasher.update(entry.name.as_bytes());
        hasher.update(b"=");
        hasher.update(entry.value_base64_url.as_bytes());
        hasher.update(b"\n");
    }
    hasher.update(b"git.authorName=");
    hasher.update(operation.git.author_name.as_bytes());
    hasher.update(b"\ngit.authorEmail=");
    hasher.update(operation.git.author_email.as_bytes());
    hasher.update(b"\ngit.threadUrl=");
    hasher.update(operation.git.thread_url.as_bytes());
    hasher.update(b"\ngit.signingEnabled=");
    hasher.update(if operation.git.signing_enabled {
        b"true" as &[u8]
    } else {
        b"false"
    });
    hasher.update(b"\ngit.bitbucketGateway=");
    if let Some(gateway) = &operation.git.bitbucket_gateway {
        hasher.update(gateway.origin.as_bytes());
    }
    hasher.update(b"\n");
    format!("{:x}", hasher.finalize())
}

/// Hash of the `.env` fragment and Git configuration as they are on disk.
/// Both must be private regular files; anything else is an error.
fn written_files(paths: &EnvironmentPaths) -> io::Result<String> {
    let home = open_home_directory(paths)?;
    let fragment = read_private_bytes(&home, ENVIRONMENT_FILE)?;
    let state = open_private_dir(&paths.state_directory, None)?;
    let git = read_private_bytes(&state, GIT_CONFIG_FILE)?;
    let mut hasher = Sha256::new();
    hasher.update(b"dxd-environment-files-v1\n");
    hasher.update((fragment.len() as u64).to_be_bytes());
    hasher.update(&fragment);
    hasher.update(&git);
    Ok(format!("{:x}", hasher.finalize()))
}

pub fn base_environment_for(
    values: &BTreeMap<String, String>,
    home: &Path,
    user: &str,
) -> BTreeMap<String, String> {
    let home = home.to_string_lossy().into_owned();
    let workload_identity_socket = std::env::var("DX_WORKLOAD_IDENTITY_SOCKET")
        .ok()
        .filter(|value| Path::new(value).is_absolute())
        .unwrap_or_else(|| "/home/user/.local/state/dxd/workload-identity.sock".into());
    let mut environment = BTreeMap::from([
        ("HOME".into(), home.clone()),
        ("USER".into(), user.into()),
        ("LOGNAME".into(), user.into()),
        ("SHELL".into(), "/bin/bash".into()),
        (
            "PATH".into(),
            format!("{home}/.local/bin:/usr/local/bin:/usr/bin:/bin"),
        ),
        ("LANG".into(), "C.UTF-8".into()),
        (
            "DX_WORKLOAD_IDENTITY_SOCKET".into(),
            workload_identity_socket,
        ),
    ]);
    environment.extend(values.clone());
    environment
}

pub fn install_git_config(state_directory: &Path, git: &GitConfiguration) -> io::Result<()> {
    if git.author_name.is_empty()
        || git.author_name.len() > 256
        || git.author_email.is_empty()
        || git.author_email.len() > 256
        || git.author_name.contains(['\r', '\n', '\0'])
        || git.author_email.contains(['\r', '\n', '\0'])
        || !valid_thread_url(&git.thread_url)
        || git.bitbucket_gateway.as_ref().is_some_and(|gateway| {
            !gateway.origin.starts_with("https://")
                || gateway.origin.len() > 255
                || !gateway.origin.bytes().all(|byte| {
                    byte.is_ascii_alphanumeric() || matches!(byte, b':' | b'/' | b'.' | b'-')
                })
        })
    {
        return Err(io::ErrorKind::InvalidInput.into());
    }
    let path = state_directory.join(GIT_CONFIG_FILE);
    let signing_helper = state_directory.join("git-sign");
    let credential_helper = state_directory.join("git-credential");
    for (helper, command) in [
        (&signing_helper, "git-sign"),
        (&credential_helper, "git-credential"),
    ] {
        write_private(
            helper,
            format!("#!/bin/sh\nexec dxd {command} \"$@\"\n").as_bytes(),
            0o700,
        )?;
    }
    for hook_name in [
        "applypatch-msg",
        "pre-applypatch",
        "post-applypatch",
        "pre-commit",
        "pre-merge-commit",
        "prepare-commit-msg",
        "commit-msg",
        "post-commit",
        "pre-rebase",
        "post-checkout",
        "post-merge",
        "pre-push",
        "pre-receive",
        "update",
        "proc-receive",
        "post-receive",
        "post-update",
        "reference-transaction",
        "push-to-checkout",
        "pre-auto-gc",
        "post-rewrite",
        "sendemail-validate",
        "fsmonitor-watchman",
        "p4-changelist",
        "p4-prepare-changelist",
        "p4-post-changelist",
        "p4-pre-submit",
        "post-index-change",
    ] {
        let trailer = if hook_name == "commit-msg" {
            "thread_url=$(git config --global --get dx.threadUrl)\ngit interpret-trailers --if-exists replace --if-missing add --trailer \"dx-Thread-Id: $thread_url\" --in-place \"$1\"\n"
        } else {
            ""
        };
        let hook = state_directory.join(hook_name);
        write_private(
            &hook,
            format!(
                "#!/bin/sh\nset -eu\nrepository_git_dir=$(git rev-parse --git-common-dir 2>/dev/null || true)\nif [ -n \"$repository_git_dir\" ]; then\n  repository_hook=$repository_git_dir/hooks/{hook_name}\n  if [ -x \"$repository_hook\" ]; then\n    \"$repository_hook\" \"$@\"\n  fi\nfi\n{trailer}"
            )
            .as_bytes(),
            0o700,
        )?;
    }
    let bitbucket = git.bitbucket_gateway.as_ref().map_or_else(String::new, |gateway| {
        format!(
            "[url \"{}/api/source/bitbucket/git/\"]\n\tinsteadOf = https://bitbucket.org/\n\tinsteadOf = git@bitbucket.org:\n\tinsteadOf = ssh://git@bitbucket.org/\n",
            gateway.origin,
        )
    });
    let content = format!(
        "# Generated by dx; do not edit.\n[commit]\n\tgpgsign = {}\n[core]\n\thooksPath = {}\n[dx]\n\tthreadUrl = {}\n[gpg]\n\tformat = ssh\n[gpg \"ssh\"]\n\tprogram = {}\n[user]\n\tname = {}\n\temail = {}\n\tsigningkey = dx-managed\n[credential]\n\thelper =\n\thelper = {}\n\tuseHttpPath = true\n\tinteractive = false\n[url \"https://github.com/\"]\n\tinsteadOf = git@github.com:\n\tinsteadOf = ssh://git@github.com/\n",
        git.signing_enabled,
        git_config_value(&state_directory.to_string_lossy()),
        git_config_value(&git.thread_url),
        signing_helper.display(),
        git_config_value(&git.author_name),
        git_config_value(&git.author_email),
        credential_helper.display(),
    );
    write_private(&path, format!("{content}{bitbucket}").as_bytes(), 0o600)
}

fn write_private(path: &Path, bytes: &[u8], mode: u32) -> io::Result<()> {
    fs::write(path, bytes)?;
    set_mode(path, mode)
}

fn set_mode(path: &Path, mode: u32) -> io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(mode))
}

/// Core's `DxdThreadUrl`: `https://<host>[:port]` or a loopback
/// `http://` origin, then `/threads/<Thread id>`.
fn valid_thread_url(value: &str) -> bool {
    let (host_ok, rest): (fn(&str) -> bool, &str) =
        if let Some(rest) = value.strip_prefix("https://") {
            (
                |host| {
                    !host.is_empty()
                        && host
                            .bytes()
                            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'-'))
                },
                rest,
            )
        } else if let Some(rest) = value.strip_prefix("http://") {
            (
                |host| matches!(host, "localhost" | "127.0.0.1" | "[::1]"),
                rest,
            )
        } else {
            return false;
        };
    let Some((authority, id)) = rest.split_once("/threads/") else {
        return false;
    };
    let (host, port) = match authority.strip_prefix("[::1]") {
        Some(port) => ("[::1]", port),
        None => authority.split_at(authority.rfind(':').unwrap_or(authority.len())),
    };
    let port_ok = port.is_empty()
        || port.strip_prefix(':').is_some_and(|digits| {
            (1..=5).contains(&digits.len()) && digits.bytes().all(|byte| byte.is_ascii_digit())
        });
    let valid_thread_id = id.len() == 40
        && id.starts_with("thr_")
        && id.bytes().enumerate().all(|(index, byte)| match index {
            12 | 17 | 22 | 27 => byte == b'-',
            0..=3 => matches!(byte, b't' | b'h' | b'r' | b'_'),
            _ => byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase(),
        })
        && id.as_bytes()[18] == b'4'
        && matches!(id.as_bytes()[23], b'8' | b'9' | b'a' | b'b');
    value.len() <= 512 && host_ok(host) && port_ok && valid_thread_id
}

pub(crate) fn valid_name(name: &str) -> bool {
    let mut bytes = name.bytes();
    let Some(first) = bytes.next() else {
        return false;
    };
    name.len() <= 64
        && (first == b'_' || first.is_ascii_uppercase())
        && bytes.all(|byte| byte == b'_' || byte.is_ascii_uppercase() || byte.is_ascii_digit())
        && !RESERVED_NAMES.contains(&name)
        && !name.starts_with("CF_")
        && !name.starts_with("CLOUDFLARE_")
        && !name.starts_with("DYLD_")
}

fn decode_entries(entries: &[EnvironmentEntry]) -> io::Result<BTreeMap<String, String>> {
    if entries.len() > MAX_ENVIRONMENT_ENTRIES {
        return Err(invalid());
    }
    let mut total = 0_usize;
    let mut previous: Option<&str> = None;
    let mut values = BTreeMap::new();
    for entry in entries {
        if !valid_name(&entry.name)
            || previous.is_some_and(|name| name >= entry.name.as_str())
            || entry.value_base64_url.is_empty()
            || entry.value_base64_url.contains('=')
        {
            return Err(invalid());
        }
        let decoded = URL_SAFE_NO_PAD
            .decode(&entry.value_base64_url)
            .map_err(|_| invalid())?;
        if URL_SAFE_NO_PAD.encode(&decoded) != entry.value_base64_url
            || decoded.is_empty()
            || decoded.len() > MAX_VALUE_BYTES
            || decoded.contains(&0)
        {
            return Err(invalid());
        }
        total = total.checked_add(decoded.len()).ok_or_else(invalid)?;
        if total > MAX_TOTAL_VALUE_BYTES {
            return Err(invalid());
        }
        let value = String::from_utf8(decoded).map_err(|_| invalid())?;
        previous = Some(&entry.name);
        values.insert(entry.name.clone(), value);
    }
    Ok(values)
}

struct Fragment {
    values: BTreeMap<String, String>,
}

fn generate_fragment(values: &BTreeMap<String, String>) -> io::Result<Vec<u8>> {
    let mut generated = ENVIRONMENT_HEADER.to_vec();
    for (name, value) in values {
        generated.extend_from_slice(name.as_bytes());
        generated.extend_from_slice(b"='");
        for byte in value.as_bytes() {
            if *byte == b'\'' {
                generated.extend_from_slice(b"'\\''");
            } else {
                generated.push(*byte);
            }
        }
        generated.extend_from_slice(b"'\n");
        if generated.len() > MAX_FRAGMENT_BYTES {
            return Err(invalid());
        }
    }
    Ok(generated)
}

fn parse_fragment(bytes: &[u8]) -> io::Result<Fragment> {
    if !bytes.starts_with(ENVIRONMENT_HEADER) || bytes.len() > MAX_FRAGMENT_BYTES {
        return Err(invalid());
    }
    let mut offset = ENVIRONMENT_HEADER.len();
    let mut values: BTreeMap<String, String> = BTreeMap::new();
    while offset < bytes.len() {
        let assignment = bytes[offset..]
            .windows(2)
            .position(|candidate| candidate == b"='")
            .ok_or_else(invalid)?
            + offset;
        let name = std::str::from_utf8(&bytes[offset..assignment]).map_err(|_| invalid())?;
        if !valid_name(name)
            || values
                .last_key_value()
                .is_some_and(|(previous, _)| previous.as_str() >= name)
        {
            return Err(invalid());
        }
        offset = assignment + 2;
        let mut value = Vec::new();
        loop {
            if bytes.get(offset..offset + 2) == Some(b"'\n") {
                offset += 2;
                break;
            }
            if bytes.get(offset..offset + 4) == Some(b"'\\''") {
                value.push(b'\'');
                offset += 4;
                continue;
            }
            let byte = *bytes.get(offset).ok_or_else(invalid)?;
            if byte == 0 || byte == b'\'' {
                return Err(invalid());
            }
            value.push(byte);
            offset += 1;
        }
        if value.is_empty() || value.len() > MAX_VALUE_BYTES {
            return Err(invalid());
        }
        let value = String::from_utf8(value).map_err(|_| invalid())?;
        values.insert(name.to_owned(), value);
    }
    if values.len() > MAX_ENVIRONMENT_ENTRIES {
        return Err(invalid());
    }
    Ok(Fragment { values })
}

fn open_private_dir(path: &Path, exact_mode: Option<u32>) -> io::Result<Dir> {
    let metadata = fs::symlink_metadata(path)?;
    if metadata.file_type().is_symlink() || !metadata.is_dir() {
        return Err(io::ErrorKind::PermissionDenied.into());
    }
    verify_owner_and_mode(&metadata, exact_mode, false)?;
    Dir::open_ambient_dir(path, cap_std::ambient_authority())
}

fn verify_owner_and_mode(
    metadata: &fs::Metadata,
    exact_mode: Option<u32>,
    single_link: bool,
) -> io::Result<()> {
    use std::os::unix::fs::MetadataExt;
    // SAFETY: geteuid and getegid have no preconditions.
    let owner = unsafe { (libc::geteuid(), libc::getegid()) };
    let mode = metadata.mode() & 0o777;
    let mode_ok = match exact_mode {
        Some(exact) => mode == exact,
        None => mode & 0o022 == 0,
    };
    if metadata.uid() != owner.0
        || metadata.gid() != owner.1
        || !mode_ok
        || (single_link && metadata.nlink() != 1)
    {
        return Err(io::ErrorKind::PermissionDenied.into());
    }
    Ok(())
}

fn ensure_state_directory(paths: &EnvironmentPaths) -> io::Result<Dir> {
    match fs::create_dir(&paths.state_directory) {
        Ok(()) => set_mode(&paths.state_directory, 0o700)?,
        Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {}
        Err(error) => return Err(error),
    }
    open_private_dir(&paths.state_directory, Some(0o700))
}

fn open_home_directory(paths: &EnvironmentPaths) -> io::Result<Dir> {
    open_private_dir(&paths.home, None)
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// The hook for these paths. The asset's second line names the guest paths;
/// local development substitutes its own there, so both share one body.
fn profile_hook(paths: &EnvironmentPaths) -> String {
    let (version, rest) = PROFILE_HOOK.split_once('\n').unwrap_or_default();
    let (_, body) = rest.split_once('\n').unwrap_or_default();
    format!(
        "{version}\n__dx_home={} __dx_user={} __dx_state={}\n{body}",
        shell_quote(&paths.home.to_string_lossy()),
        shell_quote(&paths.user),
        shell_quote(&paths.state_directory.to_string_lossy()),
    )
}

/// Write the hook when it differs, atomically, owner-only. A missing or
/// replaced hook is simply rewritten: nothing else depends on its bytes.
fn install_profile(paths: &EnvironmentPaths) -> io::Result<()> {
    let directory = ensure_state_directory(paths)?;
    let expected = profile_hook(paths);
    let current = directory
        .symlink_metadata(PROFILE_FILE)
        .is_ok_and(|metadata| metadata.is_file())
        && directory
            .read(PROFILE_FILE)
            .is_ok_and(|existing| existing == expected.as_bytes());
    if current {
        return Ok(());
    }
    let temporary = temporary_name();
    let mut options = OpenOptions::new();
    options.write(true).create_new(true);
    {
        use cap_std::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let result = directory
        .open_with(&temporary, &options)
        .and_then(|file| {
            let mut file = file.into_std();
            file.write_all(expected.as_bytes())?;
            file.sync_all()
        })
        .and_then(|()| directory.rename(&temporary, &directory, PROFILE_FILE))
        .and_then(|()| sync_dir(&directory));
    if result.is_err() {
        let _ = directory.remove_file(&temporary);
    }
    result
}

fn ensure_history(directory: &Dir) -> io::Result<()> {
    let name = "history";
    match directory.symlink_metadata(name) {
        Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_file() => {
            return Err(io::ErrorKind::PermissionDenied.into());
        }
        Ok(_) => {}
        Err(error) if error.kind() == io::ErrorKind::NotFound => {
            let mut options = OpenOptions::new();
            options.write(true).create_new(true);
            {
                use cap_std::fs::OpenOptionsExt;
                options.mode(0o600);
            }
            directory.open_with(name, &options)?;
        }
        Err(error) => return Err(error),
    }
    let file = directory.open(name)?.into_std();
    let metadata = file.metadata()?;
    {
        use std::os::unix::fs::PermissionsExt;
        if metadata.permissions().mode() & 0o777 != 0o600 {
            file.set_permissions(fs::Permissions::from_mode(0o600))?;
        }
    }
    verify_owner_and_mode(&file.metadata()?, Some(0o600), true)
}

fn read_fragment(directory: &Dir, name: &str) -> io::Result<Option<Fragment>> {
    match read_private_bytes(directory, name) {
        Ok(bytes) => parse_fragment(&bytes).map(Some),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(error),
    }
}

/// The bytes of a bounded, owner-only regular file; never follows a link.
fn read_private_bytes(directory: &Dir, name: &str) -> io::Result<Vec<u8>> {
    let metadata = directory.symlink_metadata(name)?;
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(io::ErrorKind::PermissionDenied.into());
    }
    let file = directory
        .open_with(name, OpenOptions::new().read(true))?
        .into_std();
    let std_metadata = file.metadata()?;
    verify_owner_and_mode(&std_metadata, Some(0o600), true)?;
    if std_metadata.len() > MAX_FRAGMENT_BYTES as u64 {
        return Err(io::ErrorKind::PermissionDenied.into());
    }
    let mut bytes = Vec::with_capacity(std_metadata.len() as usize);
    file.take(MAX_FRAGMENT_BYTES as u64 + 1)
        .read_to_end(&mut bytes)?;
    Ok(bytes)
}

/// Read the fragment if it is a private regular file; treat any other object
/// or invalid content as absent so activation rewrites it.
fn inspect_fragment(directory: &Dir, name: &str) -> io::Result<Option<Fragment>> {
    match directory.symlink_metadata(name) {
        Ok(metadata) if metadata.file_type().is_symlink() => Ok(None),
        Ok(metadata) if !metadata.is_file() => Err(io::ErrorKind::PermissionDenied.into()),
        Ok(_) => match read_fragment(directory, name) {
            Ok(fragment) => Ok(fragment),
            Err(error)
                if matches!(
                    error.kind(),
                    io::ErrorKind::InvalidData | io::ErrorKind::PermissionDenied
                ) =>
            {
                Ok(None)
            }
            Err(error) => Err(error),
        },
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(error),
    }
}

fn sync_dir(directory: &Dir) -> io::Result<()> {
    // The Dir handle itself is a path-only descriptor; fsync needs a readable one.
    directory
        .open_with(".", OpenOptions::new().read(true))?
        .into_std()
        .sync_all()
}

fn temporary_name() -> String {
    format!(
        ".dx-environment-{}.tmp",
        URL_SAFE_NO_PAD.encode(rand::random::<[u8; 16]>())
    )
}

fn cleanup_temporaries(directory: &Dir) -> io::Result<()> {
    let mut removed = false;
    for entry in directory.entries()? {
        let entry = entry?;
        let Ok(name) = entry.file_name().into_string() else {
            continue;
        };
        if !name.starts_with(".dx-environment-") || !name.ends_with(".tmp") {
            continue;
        }
        let metadata = entry.metadata()?;
        if metadata.file_type().is_symlink() || !metadata.is_file() {
            continue;
        }
        directory.remove_file(&name)?;
        removed = true;
    }
    if removed {
        sync_dir(directory)?;
    }
    Ok(())
}

fn replace_fragment(directory: &Dir, destination: &str, generated: &[u8]) -> io::Result<()> {
    cleanup_temporaries(directory)?;
    let temporary = temporary_name();
    let mut options = OpenOptions::new();
    options.write(true).create_new(true);
    {
        use cap_std::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let mut file = directory.open_with(&temporary, &options)?.into_std();
    let result = (|| {
        file.write_all(generated)?;
        file.sync_all()?;
        verify_owner_and_mode(&file.metadata()?, Some(0o600), true)?;
        // A symlink or non-regular file at the destination is replaced by the
        // rename; a private regular file is overwritten atomically.
        directory.rename(&temporary, directory, destination)?;
        sync_dir(directory)?;
        let verified = read_fragment(directory, destination)?
            .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "environment unavailable"))?;
        let reparsed = parse_fragment(generated)?;
        if verified.values != reparsed.values {
            return Err(invalid());
        }
        Ok(())
    })();
    if result.is_err() && directory.remove_file(&temporary).is_ok() {
        let _ = sync_dir(directory);
    }
    result
}

fn remove_legacy_fragment(state_directory: &Dir) -> io::Result<()> {
    match state_directory.symlink_metadata(LEGACY_ENVIRONMENT_FILE) {
        Ok(metadata) if metadata.file_type().is_symlink() || metadata.is_file() => {
            state_directory.remove_file(LEGACY_ENVIRONMENT_FILE)?;
            sync_dir(state_directory)
        }
        Ok(_) => Err(io::ErrorKind::PermissionDenied.into()),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error),
    }
}

enum ResumeError {
    Io(io::Error),
    Timeout,
}

impl From<io::Error> for ResumeError {
    fn from(error: io::Error) -> Self {
        Self::Io(error)
    }
}

fn run_resume(
    root: &Path,
    values: &BTreeMap<String, String>,
    paths: &EnvironmentPaths,
) -> Result<(), ResumeError> {
    let hook = root.join(".agents/resume");
    let metadata = match fs::symlink_metadata(&hook) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(error.into()),
    };
    if !metadata.is_file() || metadata.file_type().is_symlink() || !is_executable(&metadata) {
        return Err(io::Error::from(io::ErrorKind::PermissionDenied).into());
    }
    let mut child = Command::new(&hook)
        .current_dir(root)
        .env_clear()
        .envs(base_environment_for(values, &paths.home, &paths.user))
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()?;
    let deadline = std::time::Instant::now() + RESUME_TIMEOUT;
    loop {
        match child.try_wait()? {
            Some(status) if status.success() => return Ok(()),
            Some(_) => return Err(io::Error::other("resume unavailable").into()),
            None if std::time::Instant::now() >= deadline => {
                let _ = child.kill();
                let _ = child.wait();
                return Err(ResumeError::Timeout);
            }
            None => std::thread::sleep(Duration::from_millis(20)),
        }
    }
}

fn is_executable(metadata: &fs::Metadata) -> bool {
    use std::os::unix::fs::PermissionsExt;
    metadata.permissions().mode() & 0o111 != 0
}

fn invalid() -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, "invalid environment")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entries(values: &[(&str, &str)]) -> Vec<EnvironmentEntry> {
        values
            .iter()
            .map(|(name, value)| EnvironmentEntry {
                name: (*name).to_owned(),
                value_base64_url: URL_SAFE_NO_PAD.encode(value.as_bytes()),
            })
            .collect()
    }

    fn git() -> GitConfiguration {
        GitConfiguration {
            author_name: "Ada".into(),
            author_email: "ada@example.com".into(),
            thread_url: "https://dx.example/threads/thr_0123abcd-4567-4abc-8def-0123456789ab"
                .into(),
            signing_enabled: false,
            bitbucket_gateway: None,
        }
    }

    fn prepare(root: &Path) -> EnvironmentPaths {
        let paths = EnvironmentPaths::test(root);
        fs::create_dir_all(&paths.home).unwrap();
        set_mode(&paths.home, 0o700).unwrap();
        paths
    }

    #[test]
    fn the_guest_hook_is_the_asset_and_local_hooks_share_its_body() {
        assert_eq!(profile_hook(&EnvironmentPaths::production()), PROFILE_HOOK);
        let local = EnvironmentPaths::local("/tmp/it's home".into(), "/tmp/state".into());
        let hook = profile_hook(&local);
        assert!(hook.contains("__dx_home='/tmp/it'\\''s home' "));
        assert!(hook.contains("__dx_state='/tmp/state/dx-terminal'\n"));
        assert!(hook.ends_with(PROFILE_HOOK.splitn(3, '\n').nth(2).unwrap()));
    }

    /// The root stub reads whatever hook this release wrote; an older hook,
    /// or none at all, never blocks activation.
    #[test]
    fn stub_sources_the_hook_this_release_writes() {
        let root = tempfile::tempdir().unwrap();
        let workspace = root.path().join("repo");
        fs::create_dir_all(&workspace).unwrap();
        let paths = prepare(root.path());
        let hook = paths.state_directory.join(PROFILE_FILE);
        let stub = root.path().join("dx-terminal.sh");
        fs::write(
            &stub,
            PROFILE_STUB.replace(
                "/home/user/.local/state/dx-terminal/profile",
                &hook.to_string_lossy(),
            ),
        )
        .unwrap();
        let shell = |flags: &str, script: &str| {
            let output = Command::new("/bin/bash")
                .arg(flags)
                .arg(format!(". '{}'\n{script}", stub.display()))
                .env_clear()
                .env("PATH", "/usr/bin:/bin")
                .stdin(Stdio::null())
                .output()
                .unwrap();
            (
                output.status.code(),
                String::from_utf8(output.stdout).unwrap(),
            )
        };

        // Before dxd ever ran: nothing to source, commands keep their status.
        assert_eq!(shell("-euc", "echo ok"), (Some(0), "ok\n".into()));

        // Starting writes the hook; an older release's hook is replaced.
        fs::create_dir_all(&paths.state_directory).unwrap();
        set_mode(&paths.state_directory, 0o700).unwrap();
        fs::write(&hook, "# dxd-profile-v3\nexport STALE=1\n").unwrap();
        let mut runtime = EnvironmentRuntime::new(paths.clone());
        assert_eq!(fs::read_to_string(&hook).unwrap(), profile_hook(&paths));
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                fs::metadata(&hook).unwrap().permissions().mode() & 0o777,
                0o600
            );
        }

        // Activation rewrites a hook that went missing and applies values.
        fs::remove_file(&hook).unwrap();
        let operation = EnvironmentActivate {
            generation: 1,
            entries: entries(&[("A", "one two")]),
            git: git(),
        };
        let materialized = runtime
            .admit(&operation)
            .ok()
            .unwrap()
            .materialize(&workspace);
        assert_eq!(materialized.outcome, EnvironmentOutcome::Applied);
        runtime.complete(&materialized);
        assert!(hook.is_file());

        // A non-interactive login shell under `set -eu` gets the exported
        // values and keeps its own exit status; allexport is restored.
        let (status, stdout) = shell(
            "-euc",
            "case $- in *a*) echo allexport ;; esac\nprintf '%s|%s|%s|%s\\n' \"$(bash -c 'printf %s \"$A\"')\" \"$HOME\" \"$GIT_CONFIG_GLOBAL\" \"$(umask)\"\nexit 3",
        );
        assert_eq!(status, Some(3));
        assert_eq!(
            stdout,
            format!(
                "one two|{}|{}|0077\n",
                paths.home.display(),
                paths.state_directory.join(GIT_CONFIG_FILE).display()
            )
        );
        // An interactive shell flushes history on exit and still exits 0.
        let (status, _) = shell("-ic", "echo probe >/dev/null");
        assert_eq!(status, Some(0));
        assert!(paths.state_directory.join("history").is_file());
    }

    #[test]
    fn validates_bounds_order_canonical_encoding_and_reserved_names() {
        assert!(decode_entries(&entries(&[("A", "1"), ("B", "2")])).is_ok());
        assert!(decode_entries(&entries(&[("B", "1"), ("A", "2")])).is_err());
        assert!(decode_entries(&entries(&[("PATH", "x")])).is_err());
        assert!(decode_entries(&entries(&[("CF_X", "x")])).is_err());
        assert!(decode_entries(&entries(&[("lower", "x")])).is_err());
        let mut padded = entries(&[("A", "ab")]);
        padded[0].value_base64_url.push('=');
        assert!(decode_entries(&padded).is_err());
        assert!(
            decode_entries(&[EnvironmentEntry {
                name: "A".into(),
                value_base64_url: URL_SAFE_NO_PAD.encode(vec![b'x'; MAX_VALUE_BYTES + 1]),
            }])
            .is_err()
        );
    }

    #[test]
    fn canonical_fragment_round_trips_and_quotes_safely() {
        let values = BTreeMap::from([
            ("A".to_owned(), "it's".to_owned()),
            ("B".to_owned(), "line\nbreak $HOME `x`".to_owned()),
        ]);
        let generated = generate_fragment(&values).unwrap();
        assert!(generated.starts_with(ENVIRONMENT_HEADER));
        assert_eq!(parse_fragment(&generated).unwrap().values, values);
        {
            let output = Command::new("/bin/bash")
                .arg("-c")
                .arg("set -a; . /dev/stdin; printf '%s|%s' \"$A\" \"$B\"")
                .stdin(Stdio::piped())
                .stdout(Stdio::piped())
                .spawn()
                .and_then(|mut child| {
                    child.stdin.take().unwrap().write_all(&generated)?;
                    child.wait_with_output()
                })
                .unwrap();
            assert_eq!(
                String::from_utf8(output.stdout).unwrap(),
                "it's|line\nbreak $HOME `x`"
            );
        }
    }

    #[test]
    fn routes_every_bitbucket_remote_through_the_gateway() {
        let directory = tempfile::tempdir().unwrap();
        install_git_config(
            directory.path(),
            &GitConfiguration {
                bitbucket_gateway: Some(GitBitbucketGateway {
                    origin: "https://dx.example.test".into(),
                }),
                ..git()
            },
        )
        .unwrap();
        for remote in [
            "https://bitbucket.org/space/one.git",
            "git@bitbucket.org:other/two.git",
        ] {
            let output = Command::new("git")
                .args(["ls-remote", "--get-url", remote])
                .env_clear()
                .env("GIT_CONFIG_GLOBAL", directory.path().join(GIT_CONFIG_FILE))
                .env("GIT_CONFIG_NOSYSTEM", "1")
                .env("PATH", "/usr/bin:/bin")
                .output()
                .unwrap();
            let path = remote.rsplit(['/', ':']).take(2).collect::<Vec<_>>();
            assert_eq!(
                String::from_utf8(output.stdout).unwrap().trim(),
                format!(
                    "https://dx.example.test/api/source/bitbucket/git/{}/{}",
                    path[1], path[0]
                )
            );
        }
    }

    #[test]
    fn digest_is_deterministic_and_covers_git_configuration() {
        let operation = EnvironmentActivate {
            generation: 1,
            entries: entries(&[("A", "1")]),
            git: git(),
        };
        let first = activation_digest(&operation);
        assert_eq!(first, activation_digest(&operation));
        let mut other = EnvironmentActivate {
            generation: 9,
            entries: entries(&[("A", "1")]),
            git: git(),
        };
        assert_eq!(
            first,
            activation_digest(&other),
            "generation is not part of the digest"
        );
        other.git.signing_enabled = true;
        assert_ne!(first, activation_digest(&other));
    }

    #[test]
    fn activates_checks_and_supersedes_through_the_runtime() {
        let root = tempfile::tempdir().unwrap();
        let workspace = root.path().join("repo");
        fs::create_dir_all(&workspace).unwrap();
        let paths = prepare(root.path());
        let mut runtime = EnvironmentRuntime::new(paths.clone());
        let operation = EnvironmentActivate {
            generation: 1,
            entries: entries(&[("A", "one"), ("B", "two")]),
            git: git(),
        };
        let digest = activation_digest(&operation);
        assert_eq!(
            runtime.check(&EnvironmentCheck {
                generation: 1,
                digest: digest.clone()
            }),
            EnvironmentOutcome::Missing
        );
        let admitted = runtime.admit(&operation).ok().unwrap();
        let materialized = admitted.materialize(&workspace);
        assert_eq!(materialized.outcome, EnvironmentOutcome::Applied);
        assert!(materialized.changed);
        runtime.complete(&materialized);
        assert_eq!(
            runtime.check(&EnvironmentCheck {
                generation: 1,
                digest: digest.clone()
            }),
            EnvironmentOutcome::Unchanged
        );
        assert_eq!(
            runtime.check(&EnvironmentCheck {
                generation: 1,
                digest: "0".repeat(64)
            }),
            EnvironmentOutcome::Missing
        );
        let fragment = fs::read(paths.home.join(".env")).unwrap();
        assert_eq!(
            parse_fragment(&fragment).unwrap().values,
            BTreeMap::from([
                ("A".to_owned(), "one".to_owned()),
                ("B".to_owned(), "two".to_owned())
            ])
        );
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                fs::metadata(paths.home.join(".env"))
                    .unwrap()
                    .permissions()
                    .mode()
                    & 0o777,
                0o600
            );
        }
        assert!(paths.state_directory.join(GIT_CONFIG_FILE).is_file());
        assert!(paths.state_directory.join("commit-msg").is_file());
        assert!(paths.state_directory.join("history").is_file());

        // Same values, new generation: unchanged.
        let same = EnvironmentActivate {
            generation: 2,
            ..operation.clone()
        };
        let materialized = runtime.admit(&same).ok().unwrap().materialize(&workspace);
        assert_eq!(materialized.outcome, EnvironmentOutcome::Unchanged);
        runtime.complete(&materialized);
        assert!(matches!(
            runtime.admit(&operation),
            Err(EnvironmentOutcome::Superseded)
        ));
        assert_eq!(
            runtime.check(&EnvironmentCheck {
                generation: 1,
                digest: digest.clone()
            }),
            EnvironmentOutcome::Superseded
        );

        // Core's next activation (after a reconnect) checks with a fresh
        // generation: the same digest answers unchanged and is adopted.
        assert_eq!(
            runtime.check(&EnvironmentCheck {
                generation: 5,
                digest: digest.clone()
            }),
            EnvironmentOutcome::Unchanged
        );
        assert!(matches!(
            runtime.admit(&same),
            Err(EnvironmentOutcome::Superseded)
        ));
        assert_eq!(
            runtime.check(&EnvironmentCheck {
                generation: 6,
                digest: "0".repeat(64)
            }),
            EnvironmentOutcome::Missing
        );
    }

    #[test]
    fn checks_report_missing_after_the_written_files_change() {
        let root = tempfile::tempdir().unwrap();
        let workspace = root.path().join("repo");
        fs::create_dir_all(&workspace).unwrap();
        let paths = prepare(root.path());
        let mut runtime = EnvironmentRuntime::new(paths.clone());
        let operation = EnvironmentActivate {
            generation: 1,
            entries: entries(&[("A", "one")]),
            git: git(),
        };
        let digest = activation_digest(&operation);
        let check = |generation| EnvironmentCheck {
            generation,
            digest: digest.clone(),
        };
        let materialized = runtime
            .admit(&operation)
            .ok()
            .unwrap()
            .materialize(&workspace);
        runtime.complete(&materialized);
        assert_eq!(runtime.check(&check(1)), EnvironmentOutcome::Unchanged);

        // Another process rewrites a value in the fragment, keeping it valid.
        let fragment = paths.home.join(ENVIRONMENT_FILE);
        let edited = fs::read_to_string(&fragment).unwrap().replace("one", "two");
        fs::write(&fragment, edited).unwrap();
        assert_eq!(runtime.check(&check(2)), EnvironmentOutcome::Missing);

        // Reactivation rewrites it; then the generated Git configuration changes.
        let again = EnvironmentActivate {
            generation: 3,
            ..operation.clone()
        };
        let materialized = runtime.admit(&again).ok().unwrap().materialize(&workspace);
        runtime.complete(&materialized);
        assert_eq!(runtime.check(&check(3)), EnvironmentOutcome::Unchanged);
        let config = paths.state_directory.join(GIT_CONFIG_FILE);
        let mut content = fs::read_to_string(&config).unwrap();
        content.push_str("[core]\n\thooksPath = /tmp\n");
        fs::write(&config, content).unwrap();
        assert_eq!(runtime.check(&check(4)), EnvironmentOutcome::Missing);
    }

    #[test]
    fn resume_hook_runs_with_the_environment_and_is_bounded() {
        let root = tempfile::tempdir().unwrap();
        let workspace = root.path().join("repo");
        fs::create_dir_all(workspace.join(".agents")).unwrap();
        let marker = root.path().join("marker");
        fs::write(
            workspace.join(".agents/resume"),
            format!("#!/bin/sh\nprintf '%s' \"$A\" > '{}'\n", marker.display()),
        )
        .unwrap();
        set_mode(&workspace.join(".agents/resume"), 0o755).unwrap();
        let paths = prepare(root.path());
        let mut runtime = EnvironmentRuntime::new(paths);
        let operation = EnvironmentActivate {
            generation: 1,
            entries: entries(&[("A", "resumed")]),
            git: git(),
        };
        let materialized = runtime
            .admit(&operation)
            .ok()
            .unwrap()
            .materialize(&workspace);
        assert_eq!(materialized.outcome, EnvironmentOutcome::Applied);
        assert_eq!(fs::read_to_string(&marker).unwrap(), "resumed");
    }

    #[test]
    fn quotes_git_author_values_without_changing_them() {
        let root = tempfile::tempdir().unwrap();
        let state = root.path().join("state");
        fs::create_dir_all(&state).unwrap();
        let mut configuration = git();
        configuration.author_name = "Ada \"Countess\" Lovelace".into();
        install_git_config(&state, &configuration).unwrap();
        let content = fs::read_to_string(state.join(GIT_CONFIG_FILE)).unwrap();
        assert!(content.contains("name = \"Ada \\\"Countess\\\" Lovelace\""));
        assert!(content.contains("gpgsign = false"));
        let mut invalid = git();
        invalid.thread_url = "https://dx.example/threads/not-a-thread".into();
        assert!(install_git_config(&state, &invalid).is_err());
    }

    #[test]
    fn thread_urls_follow_cores_grammar() {
        let id = "thr_0123abcd-4567-4abc-8def-0123456789ab";
        for valid in [
            format!("https://dx.example/threads/{id}"),
            format!("https://Dx-1.example:8443/threads/{id}"),
            format!("http://localhost:5173/threads/{id}"),
            format!("http://127.0.0.1/threads/{id}"),
            format!("http://[::1]:8787/threads/{id}"),
        ] {
            assert!(valid_thread_url(&valid), "{valid}");
        }
        for invalid in [
            format!("http://dx.example/threads/{id}"),
            format!("https://user@dx.example/threads/{id}"),
            format!("https://dx.example:/threads/{id}"),
            format!("https://dx.example:123456/threads/{id}"),
            format!("https:///threads/{id}"),
            format!("https://dx.example/x/threads/{id}"),
            format!("https://dx.example/threads/{id}?q"),
            format!("https://dx.example/threads/{id}#f"),
            format!("https://dx.example/threads/{}", id.to_uppercase()),
            format!("ftp://dx.example/threads/{id}"),
        ] {
            assert!(!valid_thread_url(&invalid), "{invalid}");
        }
    }
}
