use crate::terminal::TerminalRuntime;
use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};
use std::ffi::CString;
use std::fs::{self, File, OpenOptions};
use std::io::{self, Read, Write};
use std::os::fd::{AsRawFd, FromRawFd, RawFd};
use std::os::unix::fs::{MetadataExt, OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use url::Url;

pub const STATE_DIRECTORY: &str = "/home/user/.local/state/dx-terminal";
pub const GIT_CONFIG_FILE: &str = "gitconfig";
pub const PROFILE_PATH: &str = "/etc/profile.d/dx-terminal.sh";
pub const ENVIRONMENT_FILE: &str = ".env";
pub const MAX_ENVIRONMENT_ENTRIES: usize = 300;
pub const MAX_VALUE_BYTES: usize = 32_768;
pub const MAX_TOTAL_VALUE_BYTES: usize = 9_830_400;
pub const MAX_FRAGMENT_BYTES: usize = 40 * 1_024 * 1_024;

pub const PROFILE_HOOK: &str = include_str!("../assets/dx-terminal-profile.sh");

const LEGACY_ENVIRONMENT_FILE: &str = "environment";
pub(crate) const ENVIRONMENT_HEADER: &[u8] = b"# Generated by dx\n\
# Contains entries from dx Secrets & Environment Variables settings\n\
# (personal, project, and workspace scopes; project entries override workspace entries,\n\
# and personal entries override both).\n\
# Manage entries at their source in dx Personal, Project, or Workspace Settings.\n";
const LEGACY_ENVIRONMENT_HEADER: &[u8] = b"# dxd-environment-v1\n";

const RESERVED_NAMES: &[&str] = &[
    "BASHPID",
    "BASHOPTS",
    "BASH_ENV",
    "BASH_VERSION",
    "BASH_VERSINFO",
    "BETTER_AUTH_SECRET",
    "CI",
    "COLUMNS",
    "DX_ACCESS_AUDIENCE",
    "DX_ACCESS_ISSUER",
    "DX_AUTH_TRUSTED_ORIGINS",
    "DX_AUTH_URL",
    "DX_CONFIG_ENCRYPTION_KEYS",
    "DX_E2B_TEMPLATE",
    "DX_E2B_TIMEOUT_MS",
    "DX_ENV",
    "DX_EXPERIMENTAL_FEATURE_FIXTURE",
    "DX_INTEGRATION_FORGEJO_OAUTH",
    "DX_INTEGRATION_GITHUB_APP",
    "DX_INTEGRATION_GITLAB_OAUTH",
    "DX_MANAGED_SSH_SIGNING_ENABLED",
    "DX_MODEL_DEPLOYMENT_PROVIDERS",
    "DX_MODEL_ENDPOINT_ALLOWLIST",
    "DX_RUNNER_PROFILE_CATALOG",
    "DX_STORAGE",
    "DX_WORKLOAD_IDENTITY_SOCKET",
    "ENV",
    "E2B_API_KEY",
    "EUID",
    "HISTFILE",
    "HISTFILESIZE",
    "HISTSIZE",
    "HOME",
    "HOSTNAME",
    "IFS",
    "LD_LIBRARY_PATH",
    "LD_PRELOAD",
    "LINES",
    "LOGNAME",
    "NODE_OPTIONS",
    "PATH",
    "PPID",
    "PWD",
    "SHELL",
    "SHELLOPTS",
    "SHLVL",
    "TERM",
    "TMUX",
    "TMUX_PANE",
    "UID",
    "USER",
    "_",
];

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct EnvironmentEntry {
    pub name: String,
    pub value_base64_url: String,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EnvironmentActivate {
    pub generation: u64,
    pub entries: Vec<EnvironmentEntry>,
    pub git: GitConfiguration,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct GitConfiguration {
    pub author_name: String,
    pub author_email: String,
    pub thread_url: String,
    pub signing_enabled: bool,
    pub bitbucket_gateway: Option<GitBitbucketGateway>,
}

fn git_config_value(value: &str) -> String {
    let escaped = value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\t', "\\t")
        .replace('\u{8}', "\\b");
    format!("\"{escaped}\"")
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct GitBitbucketGateway {
    pub origin: String,
    pub repository: String,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum EnvironmentOutcome {
    Applied,
    Unchanged,
    Superseded,
    Unavailable,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum EnvironmentShell {
    NoShell,
    Current,
    RestartRequired,
}

#[derive(Clone, Debug, Serialize)]
pub struct EnvironmentResult {
    pub kind: EnvironmentOutcome,
    pub generation: u64,
    pub shell: EnvironmentShell,
}

#[derive(Clone)]
pub struct EnvironmentPaths {
    state_directory: PathBuf,
    environment: &'static str,
    legacy_environment: &'static str,
    history: &'static str,
    profile: PathBuf,
    profile_owner: u32,
    home: PathBuf,
    user: String,
    local: bool,
}

impl EnvironmentPaths {
    pub fn production() -> Self {
        Self {
            state_directory: PathBuf::from(STATE_DIRECTORY),
            environment: ENVIRONMENT_FILE,
            legacy_environment: LEGACY_ENVIRONMENT_FILE,
            history: "history",
            profile: PathBuf::from(PROFILE_PATH),
            profile_owner: 0,
            home: PathBuf::from("/home/user"),
            user: "user".into(),
            local: false,
        }
    }

    pub fn local(home: PathBuf, state_root: PathBuf) -> Self {
        // SAFETY: geteuid has no preconditions.
        let profile_owner = unsafe { libc::geteuid() };
        Self {
            state_directory: state_root.join("dx-terminal"),
            environment: ENVIRONMENT_FILE,
            legacy_environment: LEGACY_ENVIRONMENT_FILE,
            history: "history",
            profile: state_root.join("dx-terminal/profile"),
            profile_owner,
            home,
            user: std::env::var("USER").unwrap_or_else(|_| "user".into()),
            local: true,
        }
    }

    #[cfg(test)]
    fn test(root: &Path) -> Self {
        Self {
            state_directory: root.join("state"),
            environment: ENVIRONMENT_FILE,
            legacy_environment: LEGACY_ENVIRONMENT_FILE,
            history: "history",
            profile: root.join("profile"),
            // SAFETY: geteuid has no preconditions.
            profile_owner: unsafe { libc::geteuid() },
            home: root.join("home"),
            user: "user".into(),
            local: false,
        }
    }
}

pub struct EnvironmentRuntime {
    paths: EnvironmentPaths,
    applied_generation: u64,
    pending_generation: Option<u64>,
    pending_changed: bool,
}

impl EnvironmentRuntime {
    pub fn new() -> Self {
        Self {
            paths: EnvironmentPaths::production(),
            applied_generation: 0,
            pending_generation: None,
            pending_changed: false,
        }
    }

    pub fn local(home: PathBuf, state_root: PathBuf) -> Self {
        Self {
            paths: EnvironmentPaths::local(home, state_root),
            applied_generation: 0,
            pending_generation: None,
            pending_changed: false,
        }
    }

    #[cfg(test)]
    fn test(paths: EnvironmentPaths) -> Self {
        Self {
            paths,
            applied_generation: 0,
            pending_generation: None,
            pending_changed: false,
        }
    }
    pub fn activate(
        &mut self,
        operation: EnvironmentActivate,
        terminal: &mut TerminalRuntime,
    ) -> EnvironmentResult {
        let generation = operation.generation;
        if generation == 0 || generation > 9_007_199_254_740_991 {
            return unavailable(generation, terminal);
        }
        if generation < self.applied_generation {
            return EnvironmentResult {
                kind: EnvironmentOutcome::Superseded,
                generation,
                shell: terminal.environment_shell(),
            };
        }
        let values = match decode_entries(&operation.entries) {
            Ok(values) => values,
            Err(_) => return unavailable(generation, terminal),
        };
        let state_directory = match ensure_state_directory(&self.paths) {
            Ok(directory) => directory,
            Err(_) => return unavailable(generation, terminal),
        };
        let environment_directory = match open_home_directory(&self.paths) {
            Ok(directory) => directory,
            Err(_) => return unavailable(generation, terminal),
        };
        if self.paths.local && ensure_local_profile(&self.paths).is_err() {
            return unavailable(generation, terminal);
        }
        if install_git_config(&self.paths.state_directory, &operation.git).is_err()
            || verify_profile(&self.paths).is_err()
            || ensure_history(&state_directory, &self.paths).is_err()
        {
            return unavailable(generation, terminal);
        }
        let existing = match inspect_fragment(&environment_directory, self.paths.environment) {
            Ok(existing) => existing,
            Err(_) => return unavailable(generation, terminal),
        };
        let legacy = match inspect_legacy_fragment(&state_directory, self.paths.legacy_environment)
        {
            Ok(legacy) => legacy,
            Err(_) => return unavailable(generation, terminal),
        };
        if generation == self.applied_generation
            && existing
                .as_ref()
                .is_none_or(|fragment| fragment.values != values)
        {
            return unavailable(generation, terminal);
        }
        let previous = existing.as_ref().or(legacy.as_ref());
        let values_changed = previous.is_none_or(|fragment| fragment.values != values);
        let fragment_names = existing
            .iter()
            .chain(legacy.iter())
            .flat_map(|fragment| fragment.values.keys().cloned())
            .collect();
        let previous_names = match terminal.previous_managed_names(&fragment_names) {
            Ok(names) => names,
            Err(_) => return unavailable(generation, terminal),
        };
        let current_names = values.keys().cloned().collect::<BTreeSet<_>>();
        let changed = values_changed || previous_names.difference(&current_names).next().is_some();
        let generated = match generate_fragment(&values) {
            Ok(generated) => generated,
            Err(_) => return unavailable(generation, terminal),
        };
        let retrying_pending = self.pending_generation == Some(generation);
        self.pending_generation = Some(generation);
        self.pending_changed |= changed;
        let materialization_changed = existing
            .as_ref()
            .is_none_or(|fragment| fragment.values != values);
        if materialization_changed
            && replace_fragment(&environment_directory, self.paths.environment, &generated).is_err()
        {
            return unavailable(generation, terminal);
        }
        if !materialization_changed && environment_directory.sync_all().is_err() {
            return unavailable(generation, terminal);
        }
        if remove_legacy_fragment(&state_directory, self.paths.legacy_environment).is_err() {
            return unavailable(generation, terminal);
        }
        let should_resume = changed || self.applied_generation == 0 || retrying_pending;
        if should_resume && run_resume(&terminal.root, &values, &self.paths).is_err() {
            return unavailable(generation, terminal);
        }
        if terminal
            .refresh_environment(
                &values,
                &previous_names,
                generation,
                changed || self.pending_changed,
            )
            .is_err()
        {
            return unavailable(generation, terminal);
        }
        self.applied_generation = generation;
        self.pending_generation = None;
        self.pending_changed = false;
        EnvironmentResult {
            kind: if changed {
                EnvironmentOutcome::Applied
            } else {
                EnvironmentOutcome::Unchanged
            },
            generation,
            shell: terminal.environment_shell(),
        }
    }
}

fn unavailable(generation: u64, terminal: &TerminalRuntime) -> EnvironmentResult {
    EnvironmentResult {
        kind: EnvironmentOutcome::Unavailable,
        generation,
        shell: terminal.environment_shell(),
    }
}

pub fn runtime_environment_at(home: &Path) -> io::Result<BTreeMap<String, String>> {
    let mut paths = EnvironmentPaths::production();
    paths.home = home.to_path_buf();
    let directory = open_home_directory(&paths)?;
    let fragment = read_fragment(&directory, paths.environment)?
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "environment unavailable"))?;
    Ok(fragment.values)
}

pub fn base_environment_for(
    values: &BTreeMap<String, String>,
    home: &Path,
    user: &str,
) -> BTreeMap<String, String> {
    let home = home.to_string_lossy().into_owned();
    let workload_identity_socket = std::env::var("DX_WORKLOAD_IDENTITY_SOCKET")
        .ok()
        .filter(|value| Path::new(value).is_absolute())
        .unwrap_or_else(|| "/home/user/.local/state/dxd/workload-identity.sock".into());
    let mut environment = BTreeMap::from([
        ("HOME".into(), home.clone()),
        ("USER".into(), user.into()),
        ("LOGNAME".into(), user.into()),
        ("SHELL".into(), "/bin/bash".into()),
        (
            "PATH".into(),
            format!("{home}/.local/bin:/usr/local/bin:/usr/bin:/bin"),
        ),
        ("LANG".into(), "C.UTF-8".into()),
        (
            "DX_WORKLOAD_IDENTITY_SOCKET".into(),
            workload_identity_socket,
        ),
    ]);
    environment.extend(values.clone());
    environment
}

pub fn install_git_config(state_directory: &Path, git: &GitConfiguration) -> io::Result<()> {
    if git.author_name.is_empty()
        || git.author_name.len() > 256
        || git.author_email.is_empty()
        || git.author_email.len() > 256
        || git.author_name.contains(['\r', '\n', '\0'])
        || git.author_email.contains(['\r', '\n', '\0'])
        || !valid_thread_url(&git.thread_url)
        || git.bitbucket_gateway.as_ref().is_some_and(|gateway| {
            !gateway.origin.starts_with("https://")
                || gateway.origin.len() > 255
                || !gateway.origin.bytes().all(|byte| {
                    byte.is_ascii_alphanumeric() || matches!(byte, b':' | b'/' | b'.' | b'-')
                })
                || !gateway.repository.bytes().all(|byte| {
                    byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-' | b'/')
                })
                || gateway.repository.split('/').count() != 2
        })
    {
        return Err(io::ErrorKind::InvalidInput.into());
    }
    let path = state_directory.join(GIT_CONFIG_FILE);
    let signing_helper = state_directory.join("git-sign");
    let credential_helper = state_directory.join("git-credential");
    for (helper, command) in [
        (&signing_helper, "git-sign"),
        (&credential_helper, "git-credential"),
    ] {
        fs::write(helper, format!("#!/bin/sh\nexec dxd {command} \"$@\"\n"))?;
        fs::set_permissions(helper, fs::Permissions::from_mode(0o700))?;
    }
    for hook_name in [
        "applypatch-msg",
        "pre-applypatch",
        "post-applypatch",
        "pre-commit",
        "pre-merge-commit",
        "prepare-commit-msg",
        "commit-msg",
        "post-commit",
        "pre-rebase",
        "post-checkout",
        "post-merge",
        "pre-push",
        "pre-receive",
        "update",
        "proc-receive",
        "post-receive",
        "post-update",
        "reference-transaction",
        "push-to-checkout",
        "pre-auto-gc",
        "post-rewrite",
        "sendemail-validate",
        "fsmonitor-watchman",
        "p4-changelist",
        "p4-prepare-changelist",
        "p4-post-changelist",
        "p4-pre-submit",
        "post-index-change",
    ] {
        let trailer = if hook_name == "commit-msg" {
            "thread_url=$(git config --global --get dx.threadUrl)\ngit interpret-trailers --if-exists replace --if-missing add --trailer \"dx-Thread-Id: $thread_url\" --in-place \"$1\"\n"
        } else {
            ""
        };
        let hook = state_directory.join(hook_name);
        fs::write(
            &hook,
            format!(
                "#!/bin/sh\nset -eu\nrepository_git_dir=$(git rev-parse --git-common-dir 2>/dev/null || true)\nif [ -n \"$repository_git_dir\" ]; then\n  repository_hook=$repository_git_dir/hooks/{hook_name}\n  if [ -x \"$repository_hook\" ]; then\n    \"$repository_hook\" \"$@\"\n  fi\nfi\n{trailer}"
            ),
        )?;
        fs::set_permissions(hook, fs::Permissions::from_mode(0o700))?;
    }
    let bitbucket = git.bitbucket_gateway.as_ref().map_or_else(String::new, |gateway| {
        format!(
            "[url \"{}/api/source/bitbucket/git/{}.git\"]\n\tinsteadOf = https://bitbucket.org/{}.git\n",
            gateway.origin, gateway.repository, gateway.repository,
        )
    });
    let content = format!(
        "# Generated by dx; do not edit.\n[commit]\n\tgpgsign = {}\n[core]\n\thooksPath = {}\n[dx]\n\tthreadUrl = {}\n[gpg]\n\tformat = ssh\n[gpg \"ssh\"]\n\tprogram = {}\n[user]\n\tname = {}\n\temail = {}\n\tsigningkey = dx-managed\n[credential]\n\thelper =\n\thelper = {}\n\tuseHttpPath = true\n\tinteractive = false\n",
        git.signing_enabled,
        git_config_value(&state_directory.to_string_lossy()),
        git_config_value(&git.thread_url),
        signing_helper.display(),
        git_config_value(&git.author_name),
        git_config_value(&git.author_email),
        credential_helper.display(),
    );
    fs::write(&path, format!("{content}{bitbucket}"))?;
    fs::set_permissions(path, fs::Permissions::from_mode(0o600))
}

fn valid_thread_url(value: &str) -> bool {
    let Ok(url) = Url::parse(value) else {
        return false;
    };
    let secure_origin = url.scheme() == "https"
        || (url.scheme() == "http"
            && matches!(url.host_str(), Some("localhost" | "127.0.0.1" | "::1")));
    let valid_thread_id = url.path().strip_prefix("/threads/").is_some_and(|id| {
        id.len() == 40
            && id.starts_with("thr_")
            && id.bytes().enumerate().all(|(index, byte)| match index {
                12 | 17 | 22 | 27 => byte == b'-',
                0..=3 => matches!(byte, b't' | b'h' | b'r' | b'_'),
                _ => byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase(),
            })
            && id.as_bytes()[18] == b'4'
            && matches!(id.as_bytes()[23], b'8' | b'9' | b'a' | b'b')
    });
    secure_origin
        && url.username().is_empty()
        && url.password().is_none()
        && url.query().is_none()
        && url.fragment().is_none()
        && valid_thread_id
}

#[cfg(test)]
fn base_environment(values: &BTreeMap<String, String>) -> BTreeMap<String, String> {
    base_environment_for(values, Path::new("/home/user"), "user")
}

pub(crate) fn valid_name(name: &str) -> bool {
    let mut bytes = name.bytes();
    let Some(first) = bytes.next() else {
        return false;
    };
    name.len() <= 64
        && (first == b'_' || first.is_ascii_uppercase())
        && bytes.all(|byte| byte == b'_' || byte.is_ascii_uppercase() || byte.is_ascii_digit())
        && !RESERVED_NAMES.contains(&name)
        && !name.starts_with("CF_")
        && !name.starts_with("CLOUDFLARE_")
        && !name.starts_with("DYLD_")
}

fn decode_entries(entries: &[EnvironmentEntry]) -> io::Result<BTreeMap<String, String>> {
    if entries.len() > MAX_ENVIRONMENT_ENTRIES {
        return Err(invalid());
    }
    let mut total = 0_usize;
    let mut previous: Option<&str> = None;
    let mut values = BTreeMap::new();
    for entry in entries {
        if !valid_name(&entry.name)
            || previous.is_some_and(|name| name >= entry.name.as_str())
            || entry.value_base64_url.is_empty()
            || entry.value_base64_url.contains('=')
        {
            return Err(invalid());
        }
        let decoded = URL_SAFE_NO_PAD
            .decode(&entry.value_base64_url)
            .map_err(|_| invalid())?;
        if URL_SAFE_NO_PAD.encode(&decoded) != entry.value_base64_url
            || decoded.is_empty()
            || decoded.len() > MAX_VALUE_BYTES
            || decoded.contains(&0)
        {
            return Err(invalid());
        }
        total = total.checked_add(decoded.len()).ok_or_else(invalid)?;
        if total > MAX_TOTAL_VALUE_BYTES {
            return Err(invalid());
        }
        let value = String::from_utf8(decoded).map_err(|_| invalid())?;
        previous = Some(&entry.name);
        values.insert(entry.name.clone(), value);
    }
    Ok(values)
}

struct Fragment {
    values: BTreeMap<String, String>,
}

fn generate_fragment(values: &BTreeMap<String, String>) -> io::Result<Vec<u8>> {
    let mut generated = ENVIRONMENT_HEADER.to_vec();
    for (name, value) in values {
        generated.extend_from_slice(name.as_bytes());
        generated.extend_from_slice(b"='");
        for byte in value.as_bytes() {
            if *byte == b'\'' {
                generated.extend_from_slice(b"'\\''");
            } else {
                generated.push(*byte);
            }
        }
        generated.extend_from_slice(b"'\n");
        if generated.len() > MAX_FRAGMENT_BYTES {
            return Err(invalid());
        }
    }
    Ok(generated)
}

fn parse_fragment(bytes: &[u8]) -> io::Result<Fragment> {
    if !bytes.starts_with(ENVIRONMENT_HEADER) || bytes.len() > MAX_FRAGMENT_BYTES {
        return Err(invalid());
    }
    let mut offset = ENVIRONMENT_HEADER.len();
    let mut values: BTreeMap<String, String> = BTreeMap::new();
    while offset < bytes.len() {
        let assignment = bytes[offset..]
            .windows(2)
            .position(|candidate| candidate == b"='")
            .ok_or_else(invalid)?
            + offset;
        let name = std::str::from_utf8(&bytes[offset..assignment]).map_err(|_| invalid())?;
        if !valid_name(name)
            || values
                .last_key_value()
                .is_some_and(|(previous, _)| previous.as_str() >= name)
        {
            return Err(invalid());
        }
        offset = assignment + 2;
        let mut value = Vec::new();
        loop {
            if bytes.get(offset..offset + 2) == Some(b"'\n") {
                offset += 2;
                break;
            }
            if bytes.get(offset..offset + 4) == Some(b"'\\''") {
                value.push(b'\'');
                offset += 4;
                continue;
            }
            let byte = *bytes.get(offset).ok_or_else(invalid)?;
            if byte == 0 || byte == b'\'' {
                return Err(invalid());
            }
            value.push(byte);
            offset += 1;
        }
        if value.is_empty() || value.len() > MAX_VALUE_BYTES {
            return Err(invalid());
        }
        let value = String::from_utf8(value).map_err(|_| invalid())?;
        values.insert(name.to_owned(), value);
    }
    if values.len() > MAX_ENVIRONMENT_ENTRIES {
        return Err(invalid());
    }
    Ok(Fragment { values })
}

fn parse_legacy_fragment(bytes: &[u8]) -> io::Result<Fragment> {
    if !bytes.starts_with(LEGACY_ENVIRONMENT_HEADER) || bytes.len() > MAX_FRAGMENT_BYTES {
        return Err(invalid());
    }
    let mut offset = LEGACY_ENVIRONMENT_HEADER.len();
    let mut removed: BTreeSet<String> = BTreeSet::new();
    let mut values: BTreeMap<String, String> = BTreeMap::new();
    let mut exports_started = false;
    while offset < bytes.len() {
        if bytes[offset..].starts_with(b"unset ") && !exports_started {
            offset += 6;
            let end = bytes[offset..]
                .iter()
                .position(|byte| *byte == b'\n')
                .ok_or_else(invalid)?
                + offset;
            let name = std::str::from_utf8(&bytes[offset..end]).map_err(|_| invalid())?;
            if !valid_name(name)
                || removed
                    .last()
                    .is_some_and(|previous| previous.as_str() >= name)
                || !removed.insert(name.to_owned())
            {
                return Err(invalid());
            }
            offset = end + 1;
            continue;
        }
        exports_started = true;
        if !bytes[offset..].starts_with(b"export ") {
            return Err(invalid());
        }
        offset += 7;
        let assignment = bytes[offset..]
            .windows(2)
            .position(|candidate| candidate == b"='")
            .ok_or_else(invalid)?
            + offset;
        let name = std::str::from_utf8(&bytes[offset..assignment]).map_err(|_| invalid())?;
        if !valid_name(name)
            || values
                .last_key_value()
                .is_some_and(|(previous, _)| previous.as_str() >= name)
        {
            return Err(invalid());
        }
        offset = assignment + 2;
        let mut value = Vec::new();
        loop {
            if bytes.get(offset..offset + 2) == Some(b"'\n") {
                offset += 2;
                break;
            }
            if bytes.get(offset..offset + 4) == Some(b"'\\''") {
                value.push(b'\'');
                offset += 4;
                continue;
            }
            let byte = *bytes.get(offset).ok_or_else(invalid)?;
            if byte == 0 || byte == b'\'' {
                return Err(invalid());
            }
            value.push(byte);
            offset += 1;
        }
        if value.is_empty() || value.len() > MAX_VALUE_BYTES {
            return Err(invalid());
        }
        values.insert(
            name.to_owned(),
            String::from_utf8(value).map_err(|_| invalid())?,
        );
    }
    if removed.len() > MAX_ENVIRONMENT_ENTRIES
        || values.len() > MAX_ENVIRONMENT_ENTRIES
        || removed.iter().any(|name| values.contains_key(name))
    {
        return Err(invalid());
    }
    Ok(Fragment { values })
}

fn ensure_state_directory(paths: &EnvironmentPaths) -> io::Result<File> {
    match fs::create_dir(&paths.state_directory) {
        Ok(()) => fs::set_permissions(&paths.state_directory, fs::Permissions::from_mode(0o700))?,
        Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {}
        Err(error) => return Err(error),
    }
    open_state_directory(paths)
}

fn open_state_directory(paths: &EnvironmentPaths) -> io::Result<File> {
    let directory = OpenOptions::new()
        .read(true)
        .custom_flags(libc::O_DIRECTORY | libc::O_NOFOLLOW | libc::O_CLOEXEC)
        .open(&paths.state_directory)?;
    let metadata = directory.metadata()?;
    // SAFETY: geteuid and getegid have no preconditions.
    let owner = unsafe { (libc::geteuid(), libc::getegid()) };
    if !metadata.is_dir()
        || metadata.uid() != owner.0
        || metadata.gid() != owner.1
        || metadata.mode() & 0o777 != 0o700
    {
        return Err(io::ErrorKind::PermissionDenied.into());
    }
    Ok(directory)
}

fn open_home_directory(paths: &EnvironmentPaths) -> io::Result<File> {
    let directory = OpenOptions::new()
        .read(true)
        .custom_flags(libc::O_DIRECTORY | libc::O_NOFOLLOW | libc::O_CLOEXEC)
        .open(&paths.home)?;
    let metadata = directory.metadata()?;
    // SAFETY: geteuid and getegid have no preconditions.
    let owner = unsafe { (libc::geteuid(), libc::getegid()) };
    if !metadata.is_dir()
        || metadata.uid() != owner.0
        || metadata.gid() != owner.1
        || metadata.mode() & 0o022 != 0
    {
        return Err(io::ErrorKind::PermissionDenied.into());
    }
    Ok(directory)
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn profile_hook(paths: &EnvironmentPaths) -> String {
    if !paths.local {
        return PROFILE_HOOK.into();
    }
    let home = paths.home.to_string_lossy();
    let state = paths.state_directory.to_string_lossy();
    let path = format!("{home}/.local/bin:/usr/local/bin:/usr/bin:/bin");
    format!(
        "# dxd-profile-v2\nexport HOME={} USER={} LOGNAME={} SHELL=/bin/bash\nexport PATH={}\nexport LANG=C.UTF-8\nexport GIT_CONFIG_GLOBAL={}/{}\n__dx_environment={}/.env\nif [ -f \"$__dx_environment\" ] && [ ! -L \"$__dx_environment\" ] && [ \"$(stat -c '%u:%a' \"$__dx_environment\" 2>/dev/null)\" = \"$(id -u):600\" ]; then\n  case $- in *a*) __dx_restore_allexport=0 ;; *) __dx_restore_allexport=1; set -a ;; esac\n  . \"$__dx_environment\"\n  if [ \"$__dx_restore_allexport\" = 1 ]; then set +a; fi\n  unset __dx_restore_allexport\nfi\nunset __dx_environment\numask 077\nexport HISTFILE={}/history\nexport HISTSIZE=1000 HISTFILESIZE=1000\nshopt -s histappend\n__dx_history_flush() {{ builtin history -w \"$HISTFILE\"; }}\ncase \";${{PROMPT_COMMAND-}};\" in\n  *';__dx_history_flush;'*) ;;\n  *) PROMPT_COMMAND=\"${{PROMPT_COMMAND:+$PROMPT_COMMAND; }}__dx_history_flush\" ;;\nesac\ntrap '__dx_history_flush' EXIT\n",
        shell_quote(&home),
        shell_quote(&paths.user),
        shell_quote(&paths.user),
        shell_quote(&path),
        shell_quote(&state),
        GIT_CONFIG_FILE,
        shell_quote(&home),
        shell_quote(&state),
    )
}

fn ensure_local_profile(paths: &EnvironmentPaths) -> io::Result<()> {
    if !paths.local {
        return Ok(());
    }
    let expected = profile_hook(paths);
    match fs::read(&paths.profile) {
        Ok(existing) if existing == expected.as_bytes() => return Ok(()),
        Ok(_) => return Err(io::ErrorKind::PermissionDenied.into()),
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => return Err(error),
    }
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(&paths.profile)?;
    file.write_all(expected.as_bytes())?;
    file.sync_all()
}

fn verify_profile(paths: &EnvironmentPaths) -> io::Result<()> {
    let expected = profile_hook(paths);
    let file = OpenOptions::new()
        .read(true)
        .custom_flags(libc::O_NOFOLLOW | libc::O_CLOEXEC)
        .open(&paths.profile)?;
    let metadata = file.metadata()?;
    if !metadata.is_file()
        || metadata.uid() != paths.profile_owner
        || metadata.mode() & 0o022 != 0
        || metadata.len() != expected.len() as u64
    {
        return Err(io::ErrorKind::PermissionDenied.into());
    }
    let mut bytes = Vec::new();
    file.take(expected.len() as u64 + 1)
        .read_to_end(&mut bytes)?;
    if bytes == expected.as_bytes() {
        Ok(())
    } else {
        Err(invalid())
    }
}

fn ensure_history(directory: &File, paths: &EnvironmentPaths) -> io::Result<()> {
    let fd = openat(
        directory.as_raw_fd(),
        paths.history,
        libc::O_RDWR | libc::O_CREAT | libc::O_NOFOLLOW | libc::O_CLOEXEC,
        0o600,
    )?;
    // SAFETY: openat returned a newly owned descriptor.
    let file = unsafe { File::from_raw_fd(fd) };
    let mut metadata = file.metadata()?;
    // SAFETY: geteuid and getegid have no preconditions.
    let owner = unsafe { (libc::geteuid(), libc::getegid()) };
    if !metadata.is_file()
        || metadata.uid() != owner.0
        || metadata.gid() != owner.1
        || metadata.nlink() != 1
    {
        return Err(io::ErrorKind::PermissionDenied.into());
    }
    if metadata.mode() & 0o777 != 0o600 {
        file.set_permissions(fs::Permissions::from_mode(0o600))?;
        file.sync_all()?;
        metadata = file.metadata()?;
    }
    verify_private_file(&metadata, None)
}

fn read_fragment(directory: &File, name: &str) -> io::Result<Option<Fragment>> {
    read_parsed_fragment(directory, name, parse_fragment)
}

fn read_legacy_fragment(directory: &File, name: &str) -> io::Result<Option<Fragment>> {
    read_parsed_fragment(directory, name, parse_legacy_fragment)
}

fn read_parsed_fragment(
    directory: &File,
    name: &str,
    parse: fn(&[u8]) -> io::Result<Fragment>,
) -> io::Result<Option<Fragment>> {
    let fd = match openat(
        directory.as_raw_fd(),
        name,
        libc::O_RDONLY | libc::O_NOFOLLOW | libc::O_CLOEXEC,
        0,
    ) {
        Ok(fd) => fd,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error),
    };
    // SAFETY: openat returned a newly owned descriptor.
    let file = unsafe { File::from_raw_fd(fd) };
    let metadata = file.metadata()?;
    verify_private_file(&metadata, Some(MAX_FRAGMENT_BYTES as u64))?;
    let mut bytes = Vec::with_capacity(metadata.len() as usize);
    file.take(MAX_FRAGMENT_BYTES as u64 + 1)
        .read_to_end(&mut bytes)?;
    parse(&bytes).map(Some)
}

fn inspect_fragment(directory: &File, name: &str) -> io::Result<Option<Fragment>> {
    inspect_parsed_fragment(directory, name, read_fragment)
}

fn inspect_legacy_fragment(directory: &File, name: &str) -> io::Result<Option<Fragment>> {
    inspect_parsed_fragment(directory, name, read_legacy_fragment)
}

fn inspect_parsed_fragment(
    directory: &File,
    name: &str,
    read: fn(&File, &str) -> io::Result<Option<Fragment>>,
) -> io::Result<Option<Fragment>> {
    let fd = match openat(
        directory.as_raw_fd(),
        name,
        libc::O_PATH | libc::O_NOFOLLOW | libc::O_CLOEXEC,
        0,
    ) {
        Ok(fd) => fd,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error),
    };
    // SAFETY: openat returned a newly owned descriptor.
    let path = unsafe { File::from_raw_fd(fd) };
    let metadata = path.metadata()?;
    if metadata.file_type().is_symlink() {
        return Ok(None);
    }
    if !metadata.is_file() || metadata.nlink() != 1 {
        return Err(io::ErrorKind::PermissionDenied.into());
    }
    // SAFETY: geteuid and getegid have no preconditions.
    let owner = unsafe { (libc::geteuid(), libc::getegid()) };
    if metadata.uid() != owner.0
        || metadata.gid() != owner.1
        || metadata.mode() & 0o777 != 0o600
        || metadata.len() > MAX_FRAGMENT_BYTES as u64
    {
        return Ok(None);
    }
    match read(directory, name) {
        Ok(fragment) => Ok(fragment),
        Err(error) if error.kind() == io::ErrorKind::InvalidData => Ok(None),
        Err(error) => Err(error),
    }
}

#[cfg(test)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum MaterializationFault {
    AfterTemporaryCreate,
    AfterWrite,
    BeforeFileFsync,
    BeforeFstat,
    BeforeRename,
    AfterRename,
    BeforeParentFsync,
    BeforeReopen,
}

#[cfg(test)]
thread_local! {
    static MATERIALIZATION_FAULT: std::cell::Cell<Option<MaterializationFault>> = const { std::cell::Cell::new(None) };
}

#[cfg(test)]
fn materialization_checkpoint(point: MaterializationFault) -> io::Result<()> {
    if MATERIALIZATION_FAULT.get() == Some(point) {
        Err(io::Error::other("injected materialization failure"))
    } else {
        Ok(())
    }
}

macro_rules! materialization_checkpoint {
    ($point:ident) => {
        #[cfg(test)]
        materialization_checkpoint(MaterializationFault::$point)?;
    };
}

fn write_complete(writer: &mut impl Write, generated: &[u8]) -> io::Result<()> {
    writer.write_all(generated)
}

fn temporary_name() -> String {
    format!(
        ".dx-environment-{}.tmp",
        URL_SAFE_NO_PAD.encode(rand::random::<[u8; 16]>())
    )
}

fn valid_temporary_name(name: &str) -> bool {
    let Some(token) = name
        .strip_prefix(".dx-environment-")
        .and_then(|value| value.strip_suffix(".tmp"))
    else {
        return false;
    };
    token.len() == 22
        && token
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))
}

fn cleanup_temporaries(directory: &File) -> io::Result<()> {
    let mut removed = false;
    for entry in fs::read_dir(format!("/proc/self/fd/{}", directory.as_raw_fd()))? {
        let name = entry?
            .file_name()
            .into_string()
            .map_err(|_| io::ErrorKind::InvalidData)?;
        if !name.starts_with(".dx-environment-") || !name.ends_with(".tmp") {
            continue;
        }
        if !valid_temporary_name(&name) {
            return Err(invalid());
        }
        let fd = match openat(
            directory.as_raw_fd(),
            &name,
            libc::O_PATH | libc::O_NOFOLLOW | libc::O_CLOEXEC,
            0,
        ) {
            Ok(fd) => fd,
            Err(error) if error.kind() == io::ErrorKind::NotFound => continue,
            Err(error) => return Err(error),
        };
        // SAFETY: openat returned a newly owned descriptor.
        let file = unsafe { File::from_raw_fd(fd) };
        verify_private_file(&file.metadata()?, Some(MAX_FRAGMENT_BYTES as u64))?;
        unlinkat(directory.as_raw_fd(), &name)?;
        removed = true;
    }
    if removed {
        directory.sync_all()?;
    }
    Ok(())
}

fn replace_fragment(directory: &File, destination: &str, generated: &[u8]) -> io::Result<()> {
    cleanup_temporaries(directory)?;
    let temporary = temporary_name();
    let fd = openat(
        directory.as_raw_fd(),
        &temporary,
        libc::O_WRONLY | libc::O_CREAT | libc::O_EXCL | libc::O_NOFOLLOW | libc::O_CLOEXEC,
        0o600,
    )?;
    // SAFETY: openat returned a newly owned descriptor.
    let mut file = unsafe { File::from_raw_fd(fd) };
    let result = (|| {
        materialization_checkpoint!(AfterTemporaryCreate);
        write_complete(&mut file, generated)?;
        materialization_checkpoint!(AfterWrite);
        materialization_checkpoint!(BeforeFileFsync);
        file.sync_all()?;
        materialization_checkpoint!(BeforeFstat);
        verify_private_file(&file.metadata()?, Some(MAX_FRAGMENT_BYTES as u64))?;
        materialization_checkpoint!(BeforeRename);
        renameat(directory.as_raw_fd(), &temporary, destination)?;
        materialization_checkpoint!(AfterRename);
        materialization_checkpoint!(BeforeParentFsync);
        directory.sync_all()?;
        materialization_checkpoint!(BeforeReopen);
        let verified = read_fragment(directory, destination)?
            .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "environment unavailable"))?;
        let reparsed = parse_fragment(generated)?;
        if verified.values != reparsed.values {
            return Err(invalid());
        }
        Ok(())
    })();
    if result.is_err() && unlinkat(directory.as_raw_fd(), &temporary).is_ok() {
        let _ = directory.sync_all();
    }
    result
}

fn remove_legacy_fragment(directory: &File, name: &str) -> io::Result<()> {
    let fd = match openat(
        directory.as_raw_fd(),
        name,
        libc::O_PATH | libc::O_NOFOLLOW | libc::O_CLOEXEC,
        0,
    ) {
        Ok(fd) => fd,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(error),
    };
    // SAFETY: openat returned a newly owned descriptor.
    let path = unsafe { File::from_raw_fd(fd) };
    let metadata = path.metadata()?;
    // SAFETY: geteuid and getegid have no preconditions.
    let owner = unsafe { (libc::geteuid(), libc::getegid()) };
    if !metadata.file_type().is_symlink()
        && (!metadata.is_file()
            || metadata.uid() != owner.0
            || metadata.gid() != owner.1
            || metadata.nlink() != 1)
    {
        return Err(io::ErrorKind::PermissionDenied.into());
    }
    unlinkat(directory.as_raw_fd(), name)?;
    directory.sync_all()
}

fn verify_private_file(metadata: &fs::Metadata, max_size: Option<u64>) -> io::Result<()> {
    // SAFETY: geteuid and getegid have no preconditions.
    let owner = unsafe { (libc::geteuid(), libc::getegid()) };
    if !metadata.is_file()
        || metadata.uid() != owner.0
        || metadata.gid() != owner.1
        || metadata.mode() & 0o777 != 0o600
        || metadata.nlink() != 1
        || max_size.is_some_and(|maximum| metadata.len() > maximum)
    {
        Err(io::ErrorKind::PermissionDenied.into())
    } else {
        Ok(())
    }
}

fn run_resume(
    root: &Path,
    values: &BTreeMap<String, String>,
    paths: &EnvironmentPaths,
) -> io::Result<()> {
    let hook = root.join(".agents/resume");
    let metadata = match fs::symlink_metadata(&hook) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(error),
    };
    if !metadata.is_file() || metadata.file_type().is_symlink() || metadata.mode() & 0o111 == 0 {
        return Err(io::ErrorKind::PermissionDenied.into());
    }
    let status = Command::new(&hook)
        .current_dir(root)
        .env_clear()
        .envs(base_environment_for(values, &paths.home, &paths.user))
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()?;
    if status.success() {
        Ok(())
    } else {
        Err(io::Error::other("resume unavailable"))
    }
}

fn openat(directory: RawFd, name: &str, flags: i32, mode: u32) -> io::Result<RawFd> {
    let name = CString::new(name).map_err(|_| invalid())?;
    // SAFETY: name is NUL-terminated, directory is borrowed, and openat returns an owned fd.
    let fd = unsafe { libc::openat(directory, name.as_ptr(), flags, mode) };
    if fd < 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(fd)
    }
}

fn renameat(directory: RawFd, source: &str, destination: &str) -> io::Result<()> {
    let source = CString::new(source).map_err(|_| invalid())?;
    let destination = CString::new(destination).map_err(|_| invalid())?;
    // SAFETY: both names are NUL-terminated and both directory descriptors are borrowed.
    if unsafe { libc::renameat(directory, source.as_ptr(), directory, destination.as_ptr()) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

fn unlinkat(directory: RawFd, name: &str) -> io::Result<()> {
    let name = CString::new(name).map_err(|_| invalid())?;
    // SAFETY: name is NUL-terminated and directory is borrowed.
    if unsafe { libc::unlinkat(directory, name.as_ptr(), 0) } == 0 {
        Ok(())
    } else {
        Err(io::Error::last_os_error())
    }
}

fn invalid() -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, "invalid environment")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocol::{Dimensions, TerminalHeartbeat};
    use std::fs::hard_link;
    use std::os::unix::fs::symlink;
    use tempfile::tempdir;

    fn with_materialization_fault<T>(point: MaterializationFault, action: impl FnOnce() -> T) -> T {
        MATERIALIZATION_FAULT.set(Some(point));
        let result = action();
        MATERIALIZATION_FAULT.set(None);
        result
    }

    fn entries(values: &[(&str, &str)]) -> Vec<EnvironmentEntry> {
        values
            .iter()
            .map(|(name, value)| EnvironmentEntry {
                name: (*name).into(),
                value_base64_url: URL_SAFE_NO_PAD.encode(value.as_bytes()),
            })
            .collect()
    }

    fn wait_for_terminal_ready(terminal: &mut TerminalRuntime) {
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(3);
        while !matches!(terminal.heartbeat(), TerminalHeartbeat::Ready { .. }) {
            terminal.drain_output().unwrap();
            assert!(
                std::time::Instant::now() < deadline,
                "resident did not become ready"
            );
            std::thread::sleep(std::time::Duration::from_millis(10));
        }
    }

    #[test]
    fn validates_bounds_order_canonical_encoding_and_reserved_names() {
        assert!(decode_entries(&[]).is_ok());
        assert!(decode_entries(&entries(&[("A", "x"), ("B", "y")])).is_ok());
        assert!(decode_entries(&entries(&[("B", "x"), ("A", "y")])).is_err());
        assert!(decode_entries(&entries(&[("A", "x"), ("A", "y")])).is_err());
        assert!(decode_entries(&entries(&[("PATH", "x")])).is_err());
        let mut malformed = entries(&[("A", "x")]);
        malformed[0].value_base64_url = "eA==".into();
        assert!(decode_entries(&malformed).is_err());
        assert!(decode_entries(&entries(&[("A", "")])).is_err());
        assert!(decode_entries(&entries(&[("A", &"x".repeat(MAX_VALUE_BYTES))])).is_ok());
        assert!(decode_entries(&entries(&[("A", &"x".repeat(MAX_VALUE_BYTES + 1))])).is_err());
        for bytes in [vec![0], vec![0xff]] {
            let mut invalid_value = entries(&[("A", "x")]);
            invalid_value[0].value_base64_url = URL_SAFE_NO_PAD.encode(bytes);
            assert!(decode_entries(&invalid_value).is_err());
        }
        let mut maximum_entries = (0..MAX_ENVIRONMENT_ENTRIES)
            .map(|index| EnvironmentEntry {
                name: format!("VALUE_{index:03}"),
                value_base64_url: "eA".into(),
            })
            .collect::<Vec<_>>();
        assert!(decode_entries(&maximum_entries).is_ok());
        maximum_entries.push(EnvironmentEntry {
            name: "VALUE_300".into(),
            value_base64_url: "eA".into(),
        });
        assert!(decode_entries(&maximum_entries).is_err());
    }

    #[test]
    fn generated_bash_round_trips_data_without_execution() {
        let temporary = tempdir().unwrap();
        let marker = temporary.path().join("injected");
        let controls = (1_u8..=31).map(char::from).collect::<String>();
        let dangerous = format!(
            "quote' newline\n dollar$ backtick` slash\\ $(touch {}) ; end\n{controls}",
            marker.display(),
        );
        let values = decode_entries(&entries(&[
            ("A", &dangerous),
            ("B", "🙂"),
            ("WHITESPACE", " \t\r\n "),
        ]))
        .unwrap();
        let generated = generate_fragment(&values).unwrap();
        let parsed = parse_fragment(&generated).unwrap();
        assert_eq!(parsed.values, values);
        assert_eq!(generated, generate_fragment(&values).unwrap());
        let fragment = temporary.path().join(".env");
        fs::write(&fragment, &generated).unwrap();
        let status = Command::new("/bin/bash")
            .args([
                "--noprofile",
                "--norc",
                "-c",
                ". \"$FRAGMENT\"; [[ $A == \"$EXPECTED\" && $B == '🙂' && $WHITESPACE == $' \\t\\r\\n ' ]]",
            ])
            .env_clear()
            .env("FRAGMENT", &fragment)
            .env("EXPECTED", &dangerous)
            .status()
            .unwrap();
        assert!(status.success());
        assert!(!marker.exists());
    }

    #[test]
    fn installs_private_native_git_helpers() {
        let directory = tempfile::tempdir().unwrap();
        install_git_config(
            directory.path(),
            &GitConfiguration {
                author_name: "dxcodeagent".into(),
                author_email: "agent@dxcode.dev".into(),
                thread_url:
                    "https://dx.example.test/threads/thr_00000000-0000-4000-8000-000000000000"
                        .into(),
                signing_enabled: false,
                bitbucket_gateway: None,
            },
        )
        .unwrap();
        let config = fs::read_to_string(directory.path().join(GIT_CONFIG_FILE)).unwrap();
        assert!(config.contains("gpgsign = false"));
        assert!(config.contains("format = ssh"));
        assert!(config.contains("name = \"dxcodeagent\""));
        assert!(config.contains("email = \"agent@dxcode.dev\""));
        assert!(config.contains("signingkey = dx-managed"));
        assert!(config.contains("useHttpPath = true"));
        for helper in ["git-sign", "git-credential"] {
            let path = directory.path().join(helper);
            assert_eq!(
                fs::metadata(&path).unwrap().permissions().mode() & 0o777,
                0o700
            );
            assert!(fs::read_to_string(path).unwrap().contains("exec dxd"));
        }

        let repository = directory.path().join("repository");
        fs::create_dir(&repository).unwrap();
        let git = |arguments: &[&str]| {
            Command::new("git")
                .args(arguments)
                .current_dir(&repository)
                .env_clear()
                .env("GIT_CONFIG_GLOBAL", directory.path().join(GIT_CONFIG_FILE))
                .env("GIT_CONFIG_NOSYSTEM", "1")
                .env("PATH", "/usr/bin:/bin")
                .output()
                .unwrap()
        };
        let pre_repository_hook = Command::new(directory.path().join("reference-transaction"))
            .arg("prepared")
            .current_dir(&repository)
            .env_clear()
            .env("PATH", "/usr/bin:/bin")
            .output()
            .unwrap();
        assert!(
            pre_repository_hook.status.success(),
            "pre-repository hook failed: {}",
            String::from_utf8_lossy(&pre_repository_hook.stderr)
        );
        let initialization = git(&["init", "--quiet"]);
        assert!(
            initialization.status.success(),
            "git init failed: {}",
            String::from_utf8_lossy(&initialization.stderr)
        );
        let repository_hooks = repository.join(".git/hooks");
        let pre_commit = repository_hooks.join("pre-commit");
        fs::write(&pre_commit, "#!/bin/sh\nprintf ran > pre-commit-ran\n").unwrap();
        fs::set_permissions(&pre_commit, fs::Permissions::from_mode(0o700)).unwrap();
        let commit_message = repository_hooks.join("commit-msg");
        fs::write(
            &commit_message,
            "#!/bin/sh\nprintf '\\nProject-Hook: ran\\n' >> \"$1\"\n",
        )
        .unwrap();
        fs::set_permissions(&commit_message, fs::Permissions::from_mode(0o700)).unwrap();
        fs::write(repository.join("proof.txt"), "proof\n").unwrap();
        assert!(git(&["add", "proof.txt"]).status.success());
        assert!(
            git(&["commit", "--quiet", "-m", "Agent change"])
                .status
                .success()
        );
        let commit = git(&["show", "-s", "--format=%an%n%ae%n%B", "HEAD"]);
        assert!(commit.status.success());
        assert_eq!(
            fs::read_to_string(repository.join("pre-commit-ran")).unwrap(),
            "ran"
        );
        assert_eq!(
            String::from_utf8(commit.stdout).unwrap(),
            "dxcodeagent\nagent@dxcode.dev\nAgent change\n\nProject-Hook: ran\ndx-Thread-Id: https://dx.example.test/threads/thr_00000000-0000-4000-8000-000000000000\n\n",
        );
    }

    #[test]
    fn quotes_git_author_values_without_changing_them() {
        let directory = tempfile::tempdir().unwrap();
        let author_name = "Alice \\\"QA\\\"\t\u{8}";
        let author_email = "alice\\qa@example.invalid";
        install_git_config(
            directory.path(),
            &GitConfiguration {
                author_name: author_name.into(),
                author_email: author_email.into(),
                thread_url:
                    "https://dx.example.test/threads/thr_00000000-0000-4000-8000-000000000000"
                        .into(),
                signing_enabled: false,
                bitbucket_gateway: None,
            },
        )
        .unwrap();
        let config = directory.path().join(GIT_CONFIG_FILE);
        let name = Command::new("git")
            .args(["config", "--file"])
            .arg(&config)
            .args(["--get", "user.name"])
            .output()
            .unwrap();
        assert!(name.status.success());
        assert_eq!(
            String::from_utf8(name.stdout).unwrap(),
            format!("{author_name}\n")
        );
        let email = Command::new("git")
            .args(["config", "--file"])
            .arg(config)
            .args(["--get", "user.email"])
            .output()
            .unwrap();
        assert!(email.status.success());
        assert_eq!(
            String::from_utf8(email.stdout).unwrap(),
            format!("{author_email}\n")
        );
    }

    #[test]
    fn interactive_bash_hook_applies_environment_and_flushes_bounded_history() {
        let temporary = tempdir().unwrap();
        let state = temporary.path().join("state");
        fs::create_dir(&state).unwrap();
        fs::set_permissions(&state, fs::Permissions::from_mode(0o700)).unwrap();
        let environment = temporary.path().join(".env");
        let generated = generate_fragment(&BTreeMap::from([(
            "CONFIGURED_VALUE".to_owned(),
            "active".to_owned(),
        )]))
        .unwrap();
        fs::write(&environment, generated).unwrap();
        fs::set_permissions(&environment, fs::Permissions::from_mode(0o600)).unwrap();
        let history = state.join("history");
        fs::write(&history, []).unwrap();
        fs::set_permissions(&history, fs::Permissions::from_mode(0o600)).unwrap();
        let profile = temporary.path().join("profile.sh");
        fs::write(
            &profile,
            PROFILE_HOOK
                .replace("/home/user/.env", environment.to_str().unwrap())
                .replace(STATE_DIRECTORY, state.to_str().unwrap()),
        )
        .unwrap();
        let observation = temporary.path().join("observation");
        let mut child = Command::new("/bin/bash")
            .args(["--noprofile", "--norc", "-i"])
            .current_dir(temporary.path())
            .env_clear()
            .envs(base_environment(&BTreeMap::new()))
            .stdin(Stdio::piped())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .unwrap();
        write!(
            child.stdin.as_mut().unwrap(),
            ". '{}'\ncase $- in *a*) allexport=on ;; *) allexport=off ;; esac\nexported=$(env | grep '^CONFIGURED_VALUE=' || true)\nprintf '%s\\n' \"$CONFIGURED_VALUE|$exported|$allexport|$(type -t git)|$HISTSIZE|$HISTFILESIZE|$HISTFILE\" > '{}'\necho history-flush-marker\n",
            profile.to_string_lossy().replace('\'', "'\\''"),
            observation.to_string_lossy().replace('\'', "'\\''"),
        )
        .unwrap();
        child.stdin.as_mut().unwrap().flush().unwrap();
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(2);
        while !fs::read_to_string(&history)
            .unwrap_or_default()
            .contains("echo history-flush-marker")
            && std::time::Instant::now() < deadline
        {
            std::thread::sleep(std::time::Duration::from_millis(10));
        }
        assert!(
            fs::read_to_string(&history)
                .unwrap()
                .contains("echo history-flush-marker"),
            "prompt did not flush Bash history"
        );
        writeln!(child.stdin.as_mut().unwrap(), "exit").unwrap();
        assert!(child.wait().unwrap().success());
        assert_eq!(
            fs::read_to_string(observation).unwrap(),
            format!(
                "active|CONFIGURED_VALUE=active|off|file|1000|1000|{}\n",
                history.display()
            )
        );
        let persisted = fs::read_to_string(&history).unwrap();
        assert!(persisted.contains("exit"));
        assert!(persisted.lines().count() <= 1_000);
        assert_eq!(
            fs::metadata(history).unwrap().permissions().mode() & 0o777,
            0o600
        );

        let allexport = Command::new("/bin/bash")
            .args([
                "--noprofile",
                "--norc",
                "-c",
                "set -a; . \"$PROFILE\"; case $- in *a*) exit 0 ;; *) exit 1 ;; esac",
            ])
            .env_clear()
            .envs(base_environment(&BTreeMap::new()))
            .env("PROFILE", profile)
            .status()
            .unwrap();
        assert!(
            allexport.success(),
            "profile disabled a pre-existing allexport"
        );
    }

    #[test]
    fn canonical_fragment_is_assignment_only_sorted_and_deterministic() {
        let values = decode_entries(&entries(&[("B", "current")])).unwrap();
        let generated = generate_fragment(&values).unwrap();
        assert_eq!(
            String::from_utf8(generated.clone()).unwrap(),
            format!(
                "{}B='current'\n",
                String::from_utf8_lossy(ENVIRONMENT_HEADER)
            ),
        );
        let parsed = parse_fragment(&generated).unwrap();
        assert_eq!(parsed.values, values);
        assert!(!generated.windows(6).any(|window| window == b"export"));
        assert!(!generated.windows(5).any(|window| window == b"unset"));
    }

    #[test]
    fn generated_fragment_stays_within_the_worst_case_bound() {
        let value = "'".repeat(MAX_VALUE_BYTES);
        let values = (0..MAX_ENVIRONMENT_ENTRIES)
            .map(|index| (format!("VALUE_{index:03}"), value.clone()))
            .collect::<BTreeMap<_, _>>();
        let generated = generate_fragment(&values).unwrap();
        assert!(generated.len() <= MAX_FRAGMENT_BYTES);
        assert_eq!(parse_fragment(&generated).unwrap().values, values);
    }

    #[test]
    fn descriptor_relative_materialization_repairs_regular_files_and_replaces_symlinks() {
        let temporary = tempdir().unwrap();
        let paths = EnvironmentPaths::test(temporary.path());
        fs::create_dir(&paths.home).unwrap();
        fs::write(&paths.profile, PROFILE_HOOK).unwrap();
        fs::set_permissions(&paths.profile, fs::Permissions::from_mode(0o644)).unwrap();
        let directory = open_home_directory(&paths).unwrap();
        let generated =
            generate_fragment(&decode_entries(&entries(&[("A", "value")])).unwrap()).unwrap();
        replace_fragment(&directory, paths.environment, &generated).unwrap();
        let path = paths.home.join(paths.environment);
        assert_eq!(
            fs::metadata(&path).unwrap().permissions().mode() & 0o777,
            0o600
        );
        assert_eq!(
            read_fragment(&directory, paths.environment)
                .unwrap()
                .unwrap()
                .values["A"],
            "value"
        );

        let stale_temporary = paths
            .home
            .join(".dx-environment-0000000000000000000000.tmp");
        fs::write(&stale_temporary, "partial-private-value").unwrap();
        fs::set_permissions(&stale_temporary, fs::Permissions::from_mode(0o600)).unwrap();
        replace_fragment(&directory, paths.environment, &generated).unwrap();
        assert!(!stale_temporary.exists());
        symlink(temporary.path().join("target"), &stale_temporary).unwrap();
        assert!(replace_fragment(&directory, paths.environment, &generated).is_err());
        fs::remove_file(&stale_temporary).unwrap();

        fs::remove_file(&path).unwrap();
        symlink(temporary.path().join("target"), &path).unwrap();
        replace_fragment(&directory, paths.environment, &generated).unwrap();
        assert!(
            !fs::symlink_metadata(&path)
                .unwrap()
                .file_type()
                .is_symlink()
        );
    }

    #[test]
    fn rejects_wrong_parent_mode_profile_content_and_history_links() {
        let temporary = tempdir().unwrap();
        let paths = EnvironmentPaths::test(temporary.path());
        fs::create_dir(&paths.home).unwrap();
        fs::write(&paths.profile, "wrong").unwrap();
        fs::set_permissions(&paths.profile, fs::Permissions::from_mode(0o644)).unwrap();
        assert!(verify_profile(&paths).is_err());
        let directory = ensure_state_directory(&paths).unwrap();
        ensure_history(&directory, &paths).unwrap();
        let history = paths.state_directory.join(paths.history);
        fs::set_permissions(&history, fs::Permissions::from_mode(0o644)).unwrap();
        ensure_history(&directory, &paths).unwrap();
        assert_eq!(
            fs::metadata(&history).unwrap().permissions().mode() & 0o777,
            0o600
        );
        fs::remove_file(&history).unwrap();
        let target = temporary.path().join("target");
        fs::write(&target, "").unwrap();
        symlink(&target, &history).unwrap();
        assert!(ensure_history(&directory, &paths).is_err());
        fs::set_permissions(&paths.state_directory, fs::Permissions::from_mode(0o755)).unwrap();
        assert!(open_state_directory(&paths).is_err());
        fs::set_permissions(&paths.home, fs::Permissions::from_mode(0o777)).unwrap();
        assert!(open_home_directory(&paths).is_err());
    }

    fn activation_fixture() -> (tempfile::TempDir, EnvironmentRuntime, TerminalRuntime) {
        let temporary = tempdir().unwrap();
        let paths = EnvironmentPaths::test(temporary.path());
        fs::create_dir(&paths.home).unwrap();
        fs::write(&paths.profile, PROFILE_HOOK).unwrap();
        fs::set_permissions(&paths.profile, fs::Permissions::from_mode(0o644)).unwrap();
        let runtime = EnvironmentRuntime::test(paths);
        let mut terminal = TerminalRuntime::new(
            temporary.path().join("workspace"),
            &format!("environment-test-{}", std::process::id()),
        );
        terminal.environment_home = temporary.path().join("home");
        (temporary, runtime, terminal)
    }

    fn operation(generation: u64, values: &[(&str, &str)]) -> EnvironmentActivate {
        EnvironmentActivate {
            generation,
            entries: entries(values),
            git: GitConfiguration {
                author_name: "dx".into(),
                author_email: "dx@example.invalid".into(),
                thread_url:
                    "https://dx.example.test/threads/thr_00000000-0000-4000-8000-000000000000"
                        .into(),
                signing_enabled: true,
                bitbucket_gateway: None,
            },
        }
    }

    #[test]
    fn activation_migrates_the_legacy_snapshot_to_one_canonical_home_file() {
        let (temporary, mut runtime, mut terminal) = activation_fixture();
        fs::create_dir(temporary.path().join("workspace")).unwrap();
        let state = temporary.path().join("state");
        fs::create_dir(&state).unwrap();
        fs::set_permissions(&state, fs::Permissions::from_mode(0o700)).unwrap();
        let legacy = state.join(LEGACY_ENVIRONMENT_FILE);
        fs::write(
            &legacy,
            b"# dxd-environment-v1\nexport MIGRATED_VALUE='from-legacy'\n",
        )
        .unwrap();
        fs::set_permissions(&legacy, fs::Permissions::from_mode(0o600)).unwrap();

        let result = runtime.activate(
            operation(1, &[("MIGRATED_VALUE", "from-legacy")]),
            &mut terminal,
        );

        assert!(matches!(result.kind, EnvironmentOutcome::Unchanged));
        assert!(!legacy.exists());
        let canonical = temporary.path().join("home/.env");
        let metadata = fs::symlink_metadata(&canonical).unwrap();
        assert!(metadata.is_file() && !metadata.file_type().is_symlink());
        assert_eq!(metadata.permissions().mode() & 0o777, 0o600);
        assert_eq!(metadata.nlink(), 1);
        assert_eq!(
            runtime_environment_at(&temporary.path().join("home")).unwrap()["MIGRATED_VALUE"],
            "from-legacy"
        );
    }

    #[test]
    fn activation_repairs_replaceable_files_and_fences_generations() {
        let (temporary, mut runtime, mut terminal) = activation_fixture();
        fs::create_dir(temporary.path().join("workspace")).unwrap();
        assert!(matches!(
            runtime
                .activate(operation(1, &[("A", "one")]), &mut terminal)
                .kind,
            EnvironmentOutcome::Applied
        ));
        assert!(matches!(
            runtime
                .activate(operation(1, &[("A", "one")]), &mut terminal)
                .kind,
            EnvironmentOutcome::Unchanged
        ));
        assert!(matches!(
            runtime
                .activate(operation(1, &[("A", "different")]), &mut terminal)
                .kind,
            EnvironmentOutcome::Unavailable
        ));
        assert!(matches!(
            runtime
                .activate(operation(2, &[("A", "one")]), &mut terminal)
                .kind,
            EnvironmentOutcome::Unchanged
        ));
        assert!(matches!(
            runtime
                .activate(operation(1, &[("A", "one")]), &mut terminal)
                .kind,
            EnvironmentOutcome::Superseded
        ));

        let destination = temporary.path().join("home/.env");
        fs::write(&destination, "partial").unwrap();
        assert!(matches!(
            runtime
                .activate(operation(2, &[("A", "one")]), &mut terminal)
                .kind,
            EnvironmentOutcome::Unavailable
        ));
        assert!(matches!(
            runtime
                .activate(operation(3, &[("A", "one")]), &mut terminal)
                .kind,
            EnvironmentOutcome::Applied
        ));
        fs::set_permissions(&destination, fs::Permissions::from_mode(0o644)).unwrap();
        assert!(matches!(
            runtime
                .activate(operation(4, &[("B", "two")]), &mut terminal)
                .kind,
            EnvironmentOutcome::Applied
        ));
        assert_eq!(
            fs::metadata(&destination).unwrap().permissions().mode() & 0o777,
            0o600
        );
        fs::write(&destination, "partial").unwrap();
        assert!(matches!(
            runtime
                .activate(operation(5, &[("C", "three")]), &mut terminal)
                .kind,
            EnvironmentOutcome::Applied
        ));
        assert_eq!(
            runtime_environment_at(&temporary.path().join("home")).unwrap()["C"],
            "three"
        );
    }

    #[test]
    fn activation_replaces_symlinks_but_rejects_directories_and_hard_links() {
        let (temporary, mut runtime, mut terminal) = activation_fixture();
        fs::create_dir(temporary.path().join("workspace")).unwrap();
        let destination = temporary.path().join("home/.env");
        let target = temporary.path().join("target");
        fs::write(&target, "outside").unwrap();
        symlink(&target, &destination).unwrap();
        assert!(matches!(
            runtime
                .activate(operation(1, &[("A", "one")]), &mut terminal)
                .kind,
            EnvironmentOutcome::Applied
        ));
        assert_eq!(fs::read_to_string(&target).unwrap(), "outside");

        fs::remove_file(&destination).unwrap();
        fs::write(&destination, "stale").unwrap();
        fs::set_permissions(&destination, fs::Permissions::from_mode(0o600)).unwrap();
        hard_link(&destination, temporary.path().join("second-link")).unwrap();
        assert!(matches!(
            runtime
                .activate(operation(2, &[("B", "two")]), &mut terminal)
                .kind,
            EnvironmentOutcome::Unavailable
        ));
        fs::remove_file(temporary.path().join("second-link")).unwrap();
        fs::remove_file(&destination).unwrap();
        fs::create_dir(&destination).unwrap();
        assert!(matches!(
            runtime
                .activate(operation(3, &[("C", "three")]), &mut terminal)
                .kind,
            EnvironmentOutcome::Unavailable
        ));
    }

    #[test]
    fn complete_write_handles_short_writes_and_rejects_write_zero() {
        struct ShortWriter {
            bytes: Vec<u8>,
            maximum: usize,
            stop_after: Option<usize>,
        }
        impl Write for ShortWriter {
            fn write(&mut self, bytes: &[u8]) -> io::Result<usize> {
                if self
                    .stop_after
                    .is_some_and(|bound| self.bytes.len() >= bound)
                {
                    return Ok(0);
                }
                let length = bytes.len().min(self.maximum);
                self.bytes.extend_from_slice(&bytes[..length]);
                Ok(length)
            }

            fn flush(&mut self) -> io::Result<()> {
                Ok(())
            }
        }
        let expected = b"complete materialization";
        let mut short = ShortWriter {
            bytes: Vec::new(),
            maximum: 2,
            stop_after: None,
        };
        write_complete(&mut short, expected).unwrap();
        assert_eq!(short.bytes, expected);

        let mut stopped = ShortWriter {
            bytes: Vec::new(),
            maximum: 3,
            stop_after: Some(3),
        };
        assert_eq!(
            write_complete(&mut stopped, expected).unwrap_err().kind(),
            io::ErrorKind::WriteZero
        );
        assert_ne!(stopped.bytes, expected);
    }

    #[test]
    fn activation_converges_across_each_atomic_install_failure_window() {
        let (temporary, mut runtime, mut terminal) = activation_fixture();
        fs::create_dir(temporary.path().join("workspace")).unwrap();
        assert!(matches!(
            runtime
                .activate(operation(1, &[("VALUE", "initial")]), &mut terminal)
                .kind,
            EnvironmentOutcome::Applied
        ));
        let destination = temporary.path().join("home/.env");
        let before_rename = [
            MaterializationFault::AfterTemporaryCreate,
            MaterializationFault::AfterWrite,
            MaterializationFault::BeforeFileFsync,
            MaterializationFault::BeforeFstat,
            MaterializationFault::BeforeRename,
        ];
        let after_rename = [
            MaterializationFault::AfterRename,
            MaterializationFault::BeforeParentFsync,
            MaterializationFault::BeforeReopen,
        ];
        let mut generation = 2_u64;
        for (faults, replaced) in [(&before_rename[..], false), (&after_rename[..], true)] {
            for fault in faults {
                let previous = parse_fragment(&fs::read(&destination).unwrap())
                    .unwrap()
                    .values["VALUE"]
                    .clone();
                let next = format!("generation-{generation}");
                let outcome = with_materialization_fault(*fault, || {
                    runtime.activate(operation(generation, &[("VALUE", &next)]), &mut terminal)
                });
                assert!(matches!(outcome.kind, EnvironmentOutcome::Unavailable));
                let visible = parse_fragment(&fs::read(&destination).unwrap())
                    .unwrap()
                    .values["VALUE"]
                    .clone();
                assert_eq!(visible, if replaced { next.clone() } else { previous });
                assert!(
                    fs::read_dir(temporary.path().join("home"))
                        .unwrap()
                        .all(|entry| !entry
                            .unwrap()
                            .file_name()
                            .to_string_lossy()
                            .ends_with(".tmp"))
                );
                let retry =
                    runtime.activate(operation(generation, &[("VALUE", &next)]), &mut terminal);
                assert!(matches!(
                    retry.kind,
                    EnvironmentOutcome::Applied | EnvironmentOutcome::Unchanged
                ));
                assert_eq!(
                    parse_fragment(&fs::read(&destination).unwrap())
                        .unwrap()
                        .values["VALUE"],
                    next
                );
                generation += 1;
            }
        }
    }

    #[test]
    fn local_vertical_activation_reuses_one_snapshot_resume_tmux_and_restart() {
        let temporary = tempdir().unwrap();
        let workspace = temporary.path().join("workspace");
        fs::create_dir_all(workspace.join(".agents")).unwrap();
        let resume_observation = temporary.path().join("resume-observation");
        let resume = workspace.join(".agents/resume");
        fs::write(
            &resume,
            format!(
                "#!/bin/bash\nprintf '%s' \"$SNAPSHOT_VALUE\" > '{}'\n",
                resume_observation.to_string_lossy().replace('\'', "'\\''"),
            ),
        )
        .unwrap();
        fs::set_permissions(&resume, fs::Permissions::from_mode(0o755)).unwrap();
        let paths = EnvironmentPaths::test(temporary.path());
        fs::create_dir(&paths.home).unwrap();
        fs::write(&paths.profile, PROFILE_HOOK).unwrap();
        fs::set_permissions(&paths.profile, fs::Permissions::from_mode(0o644)).unwrap();
        let environment_home = paths.home.clone();
        let mut environment = EnvironmentRuntime::test(paths);
        let thread_id = format!("environment-vertical-{}", std::process::id());
        let session_name = format!("dx-{thread_id}");
        let mut terminal = TerminalRuntime::new(workspace.clone(), &thread_id);
        terminal.environment_home = environment_home.clone();

        assert!(matches!(
            environment
                .activate(operation(1, &[("SNAPSHOT_VALUE", "first")]), &mut terminal,)
                .kind,
            EnvironmentOutcome::Applied
        ));
        assert_eq!(fs::read_to_string(&resume_observation).unwrap(), "first");
        terminal
            .open(1, "default", "open-if-absent", None, Dimensions::INITIAL)
            .unwrap();
        wait_for_terminal_ready(&mut terminal);
        let before_daemon_restart = match terminal.heartbeat() {
            TerminalHeartbeat::Ready {
                resident_generation,
                ..
            } => resident_generation,
            _ => panic!("fresh activation did not become ready"),
        };
        drop(terminal);
        drop(environment);

        fs::write(&resume_observation, "not-revalidated").unwrap();
        let mut environment = EnvironmentRuntime::test(EnvironmentPaths::test(temporary.path()));
        let mut terminal = TerminalRuntime::new(workspace, &thread_id);
        terminal.environment_home = environment_home;
        assert!(
            Command::new("tmux")
                .args([
                    "-L",
                    &session_name,
                    "set-environment",
                    "-t",
                    &session_name,
                    "-u",
                    "SNAPSHOT_VALUE",
                ])
                .status()
                .unwrap()
                .success()
        );
        let inherited = Command::new("tmux")
            .args([
                "-L",
                &session_name,
                "show-environment",
                "-t",
                &session_name,
                "SNAPSHOT_VALUE",
            ])
            .output()
            .unwrap();
        assert!(!inherited.status.success());
        let revalidated =
            environment.activate(operation(2, &[("SNAPSHOT_VALUE", "first")]), &mut terminal);
        assert!(matches!(revalidated.kind, EnvironmentOutcome::Unchanged));
        assert!(
            matches!(revalidated.shell, EnvironmentShell::Current),
            "unexpected revalidated shell state: {:?}",
            revalidated.shell
        );
        assert_eq!(fs::read_to_string(&resume_observation).unwrap(), "first");
        let repaired = Command::new("tmux")
            .args([
                "-L",
                &session_name,
                "show-environment",
                "-t",
                &session_name,
                "SNAPSHOT_VALUE",
            ])
            .output()
            .unwrap();
        assert!(repaired.status.success());
        assert_eq!(repaired.stdout, b"SNAPSHOT_VALUE=first\n");
        terminal
            .open(1, "default", "open-if-absent", None, Dimensions::INITIAL)
            .unwrap();
        wait_for_terminal_ready(&mut terminal);
        let first_resident = match terminal.heartbeat() {
            TerminalHeartbeat::Ready {
                resident_generation,
                restart_required: false,
                ..
            } if resident_generation != before_daemon_restart => resident_generation,
            _ => panic!("daemon restart did not revalidate the resident"),
        };

        let rotated =
            environment.activate(operation(3, &[("SNAPSHOT_VALUE", "second")]), &mut terminal);
        assert!(matches!(rotated.kind, EnvironmentOutcome::Applied));
        assert!(matches!(rotated.shell, EnvironmentShell::RestartRequired));
        assert_eq!(fs::read_to_string(&resume_observation).unwrap(), "second");
        terminal
            .open(1, "default", "open-if-absent", None, Dimensions::INITIAL)
            .unwrap();
        wait_for_terminal_ready(&mut terminal);
        assert!(matches!(
            terminal.heartbeat(),
            TerminalHeartbeat::Ready {
                resident_generation,
                restart_required: true,
                ..
            } if resident_generation == first_resident
        ));

        fs::write(&resume_observation, "not-rerun").unwrap();
        let same =
            environment.activate(operation(4, &[("SNAPSHOT_VALUE", "second")]), &mut terminal);
        assert!(matches!(same.kind, EnvironmentOutcome::Unchanged));
        assert!(matches!(same.shell, EnvironmentShell::RestartRequired));
        assert_eq!(
            fs::read_to_string(&resume_observation).unwrap(),
            "not-rerun"
        );
        terminal
            .restart(1, "default", first_resident, Dimensions::INITIAL)
            .unwrap();
        wait_for_terminal_ready(&mut terminal);
        assert!(matches!(
            terminal.heartbeat(),
            TerminalHeartbeat::Ready {
                resident_generation,
                restart_required: false,
                ..
            } if resident_generation != first_resident
        ));
        drop(terminal);
        let _ = Command::new("tmux")
            .args(["-L", &session_name, "kill-server"])
            .status();
    }
}
