import { DX_GIT_CONFIG_GLOBAL } from "../workspace-assets.js";

/** `~/.local/bin` precedes system paths in terminal and agent shells. */
export const GITHUB_CLI_WRAPPER_PATH = "/home/user/.local/bin/gh";
export const GITHUB_CLI_WRAPPER_MARKER = "# Generated by dx; do not edit.";

const repositoryName = /^[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/;

/**
 * A `gh` shim that authenticates the real GitHub CLI like native Git: when the
 * caller supplied no token, it asks Git's configured dx credential helper for
 * the Thread repository's current short-lived credential and passes it to that
 * one `gh` process. Nothing is stored on disk.
 */
export const githubCliWrapper = (repository: string) => {
  if (!repositoryName.test(repository))
    throw new Error("GitHub CLI wrapper repository is invalid.");
  return `#!/bin/sh
${GITHUB_CLI_WRAPPER_MARKER}
# Authenticates gh with this Thread's repository-scoped GitHub credential.
set -eu
repository='${repository}'
case "\${1-} \${2-}" in
  "auth setup-git")
    echo "dx: Git already authenticates to GitHub through dx; gh auth setup-git is not needed." >&2
    exit 0
    ;;
  "auth login")
    echo "dx: gh is authenticated by dx for $repository. Set GH_TOKEN to use another account." >&2
    exit 1
    ;;
esac
# Version, help, and completion output never contact GitHub.
case "\${1-}" in
  ""|-v|--version|version|-h|--help|help|completion) authenticate=0 ;;
  *) authenticate=1 ;;
esac
if [ "$authenticate" = 1 ] && [ -z "\${GH_TOKEN-}" ] && [ -z "\${GITHUB_TOKEN-}" ]; then
  token=$(printf 'protocol=https\\nhost=github.com\\npath=%s.git\\n\\n' "$repository" |
    GIT_TERMINAL_PROMPT=0 GIT_CONFIG_GLOBAL=${DX_GIT_CONFIG_GLOBAL} git credential fill 2>/dev/null |
    sed -n 's/^password=//p' | head -n 1) || token=
  if [ -n "$token" ]; then
    GH_TOKEN=$token
    export GH_TOKEN
  else
    echo "dx: GitHub credentials for $repository are unavailable; gh is not authenticated." >&2
  fi
fi
IFS=:
for directory in \${PATH-}; do
  if [ -n "$directory" ] && [ -x "$directory/gh" ] && ! [ "$directory/gh" -ef "$0" ]; then
    exec "$directory/gh" "$@"
  fi
done
echo "gh is not installed in this workspace." >&2
exit 127
`;
};

const wrapperDirectory = GITHUB_CLI_WRAPPER_PATH.slice(
  0,
  GITHUB_CLI_WRAPPER_PATH.lastIndexOf("/"),
);

/**
 * Idempotently installs the wrapper passed in `DX_GH_WRAPPER`. It refreshes a
 * dx-generated file and never replaces a user's own `gh`. One guest command,
 * so it can run on every workspace activation, warm or cold. E2B runs it as
 * `bash -l -c`, which inherits the terminal profile's EXIT trap; under `set -e`
 * that trap failing turned the up-to-date early exit into status 1, so clear it.
 */
export const GITHUB_CLI_WRAPPER_INSTALL_COMMAND = `set -eu
trap - EXIT
target=${GITHUB_CLI_WRAPPER_PATH}
if test -f "$target" && ! test -L "$target" && test -x "$target" && printf '%s' "$DX_GH_WRAPPER" | cmp -s - "$target"; then exit 0; fi
if { test -e "$target" || test -L "$target"; } && ! { test -f "$target" && ! test -L "$target" && sed -n 2p "$target" | grep -qxF '${GITHUB_CLI_WRAPPER_MARKER}'; }; then exit 0; fi
mkdir -p ${wrapperDirectory}
temp=$(mktemp ${wrapperDirectory}/.gh.XXXXXX)
trap 'rm -f "$temp"' EXIT
printf '%s' "$DX_GH_WRAPPER" > "$temp"
chmod 0755 "$temp"
mv -f "$temp" "$target"`;
